ViaVersion/ViaVersion

- src/main/java/us/myles/ViaVersion/transformers/OutgoingTransformer.java
This will fix:
- Entity Relative Move
- Entity Look And Relative Move
http://wiki.vg/Pre-release_protocol#Entity_Relative_Move
> Fix move packets

- src/main/java/us/myles/ViaVersion/metadata/SoundCategory.java
- src/main/java/us/myles/ViaVersion/metadata/SoundEffect.java
- src/main/java/us/myles/ViaVersion/packets/PacketType.java
- src/main/java/us/myles/ViaVersion/transformers/OutgoingTransformer.java
Adds support for the named sound effect packet.
Also tweaked the finding of new packet ids a bit.
> Added support for named sound effect packet.

- src/main/java/us/myles/ViaVersion/metadata/MetaIndex.java
- src/main/java/us/myles/ViaVersion/sounds/SoundEffect.java
- src/main/java/us/myles/ViaVersion/transformers/OutgoingTransformer.java
Was a little typo, new index of rotation varint was 5, should be 6.
> Fixed: ItemFrame crash, remaining missing sounds and Horse Metadata

- src/main/java/us/myles/ViaVersion/PacketUtil.java
- src/main/java/us/myles/ViaVersion/transformers/IncomingTransformer.java
- src/main/java/us/myles/ViaVersion/transformers/OutgoingTransformer.java
This will use the new set passenger packet
> Fixed riding on entities.

- src/main/java/us/myles/ViaVersion/transformers/IncomingTransformer.java
- src/main/java/us/myles/ViaVersion/transformers/OutgoingTransformer.java
This still does not fix the arrows, but we're closer now!
> Fix USE_ITEM using correct item. Fix SPAWN_OBJECT velocity.

- src/main/java/us/myles/ViaVersion/metadata/MetadataRewriter.java
- src/main/java/us/myles/ViaVersion/metadata/Type.java
- src/main/java/us/myles/ViaVersion/transformers/OutgoingTransformer.java
- src/main/java/us/myles/ViaVersion/util/PacketUtil.java
> Rewrite Metadata system to read the data from the bytebuf instead of

- src/main/java/us/myles/ViaVersion/transformers/OutgoingTransformer.java
I'm not 100% confident that what I'm doing here is correct, but looking at http://wiki.vg/Pre-release_protocol#Spawn_Player I think I'm doing it right.
fixes #58
> Fix player entity meta data

- pom.xml
- src/main/java/us/myles/ViaVersion/ViaVersionPlugin.java
- src/main/java/us/myles/ViaVersion/api/ViaVersionAPI.java
- src/main/java/us/myles/ViaVersion/api/slot/ItemSlotRewriter.java
- src/main/java/us/myles/ViaVersion/commands/ViaVersionCommand.java
- src/main/java/us/myles/ViaVersion/metadata/MetadataRewriter.java
- src/main/java/us/myles/ViaVersion/transformers/IncomingTransformer.java
- src/main/java/us/myles/ViaVersion/transformers/OutgoingTransformer.java
- src/main/java/us/myles/ViaVersion/util/PacketUtil.java
- src/main/java/us/myles/ViaVersion/util/ReflectionUtil.java
- src/main/resources/plugin.yml
> support for rewriting SpawnEggs

- src/main/java/us/myles/ViaVersion/transformers/OutgoingTransformer.java
This should fix the last possible cause of issue #70
> Fix some MalformedJsonExceptions

- src/main/java/us/myles/ViaVersion/slot/ItemSlotRewriter.java
**Before:**
**After:**
This will also fix invalid book tag on empty book
> Fix book formatting and invalid book tag at empty book

- src/main/java/us/myles/ViaVersion/ViaVersionPlugin.java
- src/main/java/us/myles/ViaVersion/listeners/CommandBlockListener.java
- src/main/java/us/myles/ViaVersion/metadata/MetaIndex.java
- src/main/java/us/myles/ViaVersion/transformers/IncomingTransformer.java
- src/main/java/us/myles/ViaVersion/transformers/OutgoingTransformer.java
This will fix commandblocks. MinecartCommands are still broken.
**only 1.8 commandblock features work!**
> Fix commandblocks

- src/main/java/us/myles/ViaVersion/ViaVersionPlugin.java
- src/main/resources/config.yml
This saves lines and it is much more expandable in the future if you want to add more options to the config.
> Made the config use the default bukkit config methods insteed.

- src/main/java/us/myles/ViaVersion/metadata/MetaIndex.java
- src/main/java/us/myles/ViaVersion/metadata/MetadataRewriter.java
- src/main/java/us/myles/ViaVersion/transformers/IncomingTransformer.java
Commandblocks are now fully working
> Fix commandblock minecarts

- README.md
> Travis Build Status

- src/main/java/us/myles/ViaVersion/ViaVersionPlugin.java
- src/main/java/us/myles/ViaVersion/api/Boss/BossBar.java
- src/main/java/us/myles/ViaVersion/api/Boss/BossColor.java
- src/main/java/us/myles/ViaVersion/api/Boss/BossFlag.java
- src/main/java/us/myles/ViaVersion/api/Boss/BossStyle.java
- src/main/java/us/myles/ViaVersion/api/ViaVersionAPI.java
- src/main/java/us/myles/ViaVersion/boss/ViaBossBar.java
I'm really bad at creating javadocs. You might want to consider changing some of them
> Implement 1.9 BossBarAPI for developers

- src/main/java/us/myles/ViaVersion/transformers/OutgoingTransformer.java
I hoped I could blame @HugoDaBosss for breaking it. But sadly I couldn't
> Fix jukebox

- src/main/java/us/myles/ViaVersion/metadata/MetaIndex.java
- src/main/java/us/myles/ViaVersion/metadata/MetadataRewriter.java
- src/main/java/us/myles/ViaVersion/metadata/Type.java
- src/main/java/us/myles/ViaVersion/transformers/IncomingTransformer.java
@MylesIsCool could you fix my formatting, eclipse always fucks it up....
> Fix animation for bows

- src/main/java/us/myles/ViaVersion/ViaVersionPlugin.java
- src/main/java/us/myles/ViaVersion/transformers/OutgoingTransformer.java
- src/main/resources/config.yml
fixes error of wither entry 11 in metadata is already set by another value
same for enderdragon
> fix metadata type mismatch

- src/main/java/us/myles/ViaVersion/ViaVersionPlugin.java
- src/main/java/us/myles/ViaVersion/util/Configuration.java
Configuration reads old config and moves it's values over to a new
config copied from the resources directory.
normally, when you save it would delete the comments, but they are
written back in to the new config by this wrapper
now people their config files will actually update
> Add config wrapper to update config

- src/main/java/us/myles/ViaVersion/ConnectionInfo.java
- src/main/java/us/myles/ViaVersion/chunks/Chunk.java
- src/main/java/us/myles/ViaVersion/chunks/ChunkManager.java
- src/main/java/us/myles/ViaVersion/chunks/ChunkSection.java
- src/main/java/us/myles/ViaVersion/chunks/NibbleArray.java
- src/main/java/us/myles/ViaVersion/handlers/ViaChunkHandler.java
- src/main/java/us/myles/ViaVersion/transformers/OutgoingTransformer.java
- src/main/java/us/myles/ViaVersion/util/ReflectionUtil.java
This properly writes empty chunks and chunk unloads.
Fixes bugs where void worlds bug out when rendering chunks.
This bug was related to required chunks not being sent.
> Implement new chunk transformer

- src/main/java/us/myles/ViaVersion/transformers/IncomingTransformer.java
Just a quick fix. Code from PLAY_CLICK_WINDOW.
> Throw items when you try to put things in your second hand in creative.

- src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/ArmorType.java
Why does eclipse keep messing up my formatting, I should switch to IntelliJ....
> Small optimization for armor searching

- src/main/java/us/myles/ViaVersion/api/protocol/ProtocolVersion.java
I'm almost done checking your code, looks really really good!
> Change protocol constants to final fields

- src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/packets/PlayerPackets.java
I'm comparing the old / new transformer api, found this small bug
> Fix small teampacket bug

- README.md
Add JavaDocs link to README.md
> Add JavaDocs link to README.md

- README.md
https://github.com/Matsv/ViaVersion/blob/gitter/README.md
> Add Gitter badge to README.md

- src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/packets/SpawnPackets.java
> Handle discontinued player item in hand, fixes #299

- src/main/java/us/myles/ViaVersion/ViaVersionPlugin.java
- src/main/java/us/myles/ViaVersion/api/command/ViaSubCommand.java
- src/main/java/us/myles/ViaVersion/commands/ViaCommandHandler.java
- src/main/java/us/myles/ViaVersion/commands/defaultsubs/HelpSubCmd.java
Well, the help subcommand is not that needed, but it's good to have ;)
YOU CAN NOW TABCOMPLETE /viaversion SUBCOMMANDS YAY (and add it to your own subcommands if you ever wanted to) :smile:
> Tabcomplete

- src/main/java/us/myles/ViaVersion/ViaVersionPlugin.java
Thanks @HugoDaBosss, don't know how I missed this :O
> Woops use the same instance

- src/main/java/us/myles/ViaVersion/api/protocol/ProtocolPipeline.java
- src/main/java/us/myles/ViaVersion/api/protocol/ProtocolRegistry.java
- src/main/java/us/myles/ViaVersion/api/protocol/ProtocolVersion.java
- src/main/java/us/myles/ViaVersion/boss/ViaBossBar.java
- src/main/java/us/myles/ViaVersion/commands/defaultsubs/ListSubCmd.java
Should credit @Matsv as well for creating the ProtocolVersion class ;)
> Implement new protocol version registry

- src/main/java/us/myles/ViaVersion/api/boss/BossBar.java
- src/main/java/us/myles/ViaVersion/boss/ViaBossBar.java
> Cleanup BossBar class & add new bossbar api method, addPlayers()

- src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/ItemRewriter.java
> Fix custom NBT for potions / spawneggs

- src/main/java/us/myles/ViaVersion/commands/defaultsubs/ListSubCmd.java
Your fix didn't work Myles :cry:
> Fix viaversion list command

- src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/packets/WorldPackets.java
- src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/sounds/Effect.java
This will fix #341 and other sound effects
> Rewrite effect ids

- src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/packets/EntityPackets.java
1.8 -> Message -> String
1.9 -> Message -> Chat
> Fix Combat packet 'message' 

- src/main/java/us/myles/ViaVersion/ViaVersionPlugin.java
- src/main/java/us/myles/ViaVersion/api/ViaVersionConfig.java
- src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/Protocol1_9TO1_8.java
- src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/listeners/DeathListener.java
- src/main/resources/config.yml
https://gyazo.com/a6341d3639f87e2a7a36dd970c4dce64
> Possibility to show the new 1.9 death messages

- src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/packets/SpawnPackets.java
> Change item from offhand, to mainhand.

- src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/listeners/DeathListener.java
Nobody tried it in the last 22 days :cry: (or didn't report it) #348
> Fix death messages

- src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/Protocol1_9TO1_8.java
- src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/chat/ChatRewriter.java
- src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/chat/GameMode.java
- src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/packets/PlayerPackets.java
- src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/packets/WorldPackets.java
- src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/storage/EntityTracker.java
- src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/storage/PlaceBlockTracker.java
> Don't call PlayerInteractEvent twice and fix the gamemode message

- src/main/java/us/myles/ViaVersion/ViaVersionPlugin.java
- src/main/java/us/myles/ViaVersion/api/ViaVersionConfig.java
- src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/storage/ClientChunks.java
- src/main/java/us/myles/ViaVersion/util/ReflectionUtil.java
- src/main/resources/config.yml
> Fix anti-xray for 1.9

- src/main/java/us/myles/ViaVersion/api/PacketWrapper.java
- src/main/java/us/myles/ViaVersion/api/protocol/ProtocolPipeline.java
- src/main/java/us/myles/ViaVersion/api/protocol/ProtocolRegistry.java
- src/main/java/us/myles/ViaVersion/protocols/base/BaseProtocol.java
- src/main/java/us/myles/ViaVersion/protocols/protocol1_9_1_2to1_9_3/BlockEntity.java
- src/main/java/us/myles/ViaVersion/protocols/protocol1_9_1_2to1_9_3/Chunk1_9_3.java
- src/main/java/us/myles/ViaVersion/protocols/protocol1_9_1_2to1_9_3/Chunk1_9_3Type.java
- src/main/java/us/myles/ViaVersion/protocols/protocol1_9_1_2to1_9_3/Protocol1_9_1_2TO1_9_3.java
- src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_9_1/Protocol1_9TO1_9_1.java
Allow 1.9.4 Spigot to have 1.9-1.9.2 connect
> 1.9.4 backport

- src/main/java/us/myles/ViaVersion/ViaVersionPlugin.java
- src/main/java/us/myles/ViaVersion/api/ViaVersionAPI.java
- src/main/java/us/myles/ViaVersion/api/ViaVersionConfig.java
- src/main/java/us/myles/ViaVersion/api/protocol/ProtocolRegistry.java
- src/main/java/us/myles/ViaVersion/protocols/base/BaseProtocol.java
- src/main/resources/config.yml
Oh, and also make the maps/list concurrent inside ProtocolRegistry
> Add possibility to get the supported versions from the api and status response

- src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/Protocol1_9TO1_8.java
TacoSpigot is a fork of PaperSpigot that people use.
> Added TacoSpigot to the block place fix.

- src/main/java/us/myles/ViaVersion/ViaConfig.java
- src/main/java/us/myles/ViaVersion/api/ViaVersionConfig.java
- src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/Protocol1_9TO1_8.java
- src/main/resources/config.yml
This will fix issues if the syntax is similar to json like {test}
> Possibility to force the json transformer

- src/main/java/us/myles/ViaVersion/api/PacketWrapper.java
Fix signs are sent before the chunks on a 1.9.4 server with a 1.9-1.9.2 client
> Let the normal send go through the event loop.

- bukkit/src/main/java/us/myles/ViaVersion/bukkit/classgenerator/ClassGenerator.java
- bukkit/src/main/java/us/myles/ViaVersion/bukkit/handlers/BukkitEncodeHandler.java
- common/src/main/java/us/myles/ViaVersion/handlers/ChannelHandlerContextWrapper.java
- common/src/main/java/us/myles/ViaVersion/handlers/ViaHandler.java
\*Insert Evil Monologue Here\*, This unfortunately doesn't work with 1.9's ProtocolSupport though, but it works with 1.8 and 1.10's. This fixes #449.
> ViaProtocolSupport Fix

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_12to1_11_1/Protocol1_12To1_11_1.java
The max length of the locale was increased in 1.12-pre3; we need to undo that.
As part of the fix for [MC-111054](https://bugs.mojang.com/browse/MC-111054 "[MC-111054] Invalid lang in options.txt leads to connection error"), the max length of the locale was [raised to 16 (from 7)](http://wiki.vg/Protocol_History#1.12-pre3), and the client now makes sure that resource packs have names shorter than that length.  However, for older servers, it is still 7, and thus the server will reject it (and the client won't know that the pack's invalid beforehand).
The fix is to just silently lower the length.  The server doesn't actually use the locale anywhere, so it's fine to do this.  Those that do will only be likely to handle a max length of 7, so it's fine more or less.
**Note**: I haven't tested …
> Backport fix for MC-111054

- bukkit/src/main/java/us/myles/ViaVersion/bukkit/providers/BukkitInventoryQuickMoveProvider.java
- bukkit/src/main/java/us/myles/ViaVersion/bukkit/tasks/protocol1_12to1_11_1/BukkitInventoryUpdateTask.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_12to1_11_1/packets/InventoryPackets.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_12to1_11_1/providers/InventoryQuickMoveProvider.java
- pom.xml
Fixed the issues below (#780 & #800) and also updated Lombok to 1.16.20 so this project can be compiled with jdk9.
Tried test it with all the possible inventories i could think of and everything seemed to be working fine.
There shouldn't be any issues now when shift click moving items.
(This took a very long time to figure out.)
> Fix inventory issues + support jdk9

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/packets/InventoryPackets.java
> Rewrite StoredEnchantments

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/Protocol1_13To1_12_2.java
fix https://github.com/MylesIsCool/ViaVersion/issues/886
> fix server icon

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/packets/WorldPackets.java
Fixes https://github.com/MylesIsCool/ViaVersion/issues/893
> Fix reddust particle color for 1.13 clients

- common/src/main/java/us/myles/ViaVersion/api/protocol/ProtocolRegistry.java
- common/src/main/java/us/myles/ViaVersion/api/protocol/ProtocolVersion.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol18w31ato1_13/MetadataRewriter.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol18w31ato1_13/Protocol18w31aTO1_13.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/types/Chunk1_13Type.java
Add support for Minecraft Snapshot 18w31a
> Add support Snapshot 18w31a

- common/src/main/java/us/myles/ViaVersion/api/protocol/ProtocolRegistry.java
- common/src/main/java/us/myles/ViaVersion/api/protocol/ProtocolVersion.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol18w32ato1_13/MetadataRewriter.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol18w32ato1_13/Protocol18w32aTO1_13.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol18w32ato1_13/packets/EntityPackets.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol18w32ato1_13/packets/InventoryPackets.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol18w32ato1_13/packets/WorldPackets.java
Added support for the new blocks
Kown issue: Item remap is missing
New Item Id Mappings at 18w32a
0-442 => 0-442
443+ => id + 5
Special Thanks 
@Gerrygames and @Pokechu22
> add support for 18w32a

- common/src/main/java/us/myles/ViaVersion/api/PacketWrapper.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/types/Chunk1_13Type.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_9_1_2to1_9_3_4/chunks/ChunkSection1_9_3_4.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_9_1_2to1_9_3_4/types/Chunk1_9_3_4Type.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_9_3to1_9_1_2/chunks/ChunkSection1_9_1_2.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_9_3to1_9_1_2/types/Chunk1_9_1_2Type.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/chunks/ChunkSection1_9to1_8.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/packets/WorldPackets.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/types/ChunkType.java
This has potential to cause memory leaks
> Replace Unpooled.buffer()

- bukkit/pom.xml
- bungee/pom.xml
- common/pom.xml
- common/src/main/java/us/myles/ViaVersion/api/protocol/ProtocolRegistry.java
- common/src/main/java/us/myles/ViaVersion/api/protocol/ProtocolVersion.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13_1_pre1to1_13/MetadataRewriter.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13_1_pre1to1_13/Protocol13_1_PRE1TO1_13.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13_1_pre1to1_13/packets/EntityPackets.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13_1_pre1to1_13/packets/InventoryPackets.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13_1_pre1to1_13/packets/WorldPackets.java
- jar/pom.xml
- pom.xml
- sponge-legacy/pom.xml
- sponge/pom.xml
Add Support for 1.13.1-pre1
Fix Tag packet
> update to 1.13.1-pre1

- bukkit/src/main/java/us/myles/ViaVersion/bukkit/classgenerator/ClassGenerator.java
- bukkit/src/main/java/us/myles/ViaVersion/bukkit/platform/BukkitViaLoader.java
> ProtocolSupport  <3 ViaVersion

- bukkit/src/main/java/us/myles/ViaVersion/bukkit/classgenerator/ClassGenerator.java
Second part. It ended up being a small wrong assumption at my end. Should work  both ways now! 😄 
The only thing I am not sure of is newer versions Via doesn't support yet. Perhaps 1.14 will throw some weird errors, because I am not sure how via handles that.
> ViaVersion <3 ProtocolSupport

- bukkit/src/main/java/us/myles/ViaVersion/bukkit/platform/BukkitConfigAPI.java
- bungee/src/main/java/us/myles/ViaVersion/bungee/platform/BungeeConfigAPI.java
- common/src/main/java/us/myles/ViaVersion/api/Triple.java
- common/src/main/java/us/myles/ViaVersion/api/ViaVersionConfig.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/packets/EntityPackets.java
- common/src/main/resources/assets/viaversion/config.yml
- sponge/src/main/java/us/myles/ViaVersion/sponge/platform/SpongeConfigAPI.java
Maybe a newer version of #770 ?
> Reduce cooldown

- common/src/main/java/us/myles/ViaVersion/api/PacketWrapper.java
> Fix PacketWrapper#constructPacket

- bungee/src/main/java/us/myles/ViaVersion/bungee/service/ProtocolDetectorService.java
- common/src/main/java/us/myles/ViaVersion/api/platform/providers/ViaProviders.java
- common/src/main/java/us/myles/ViaVersion/api/protocol/Protocol.java
- common/src/main/java/us/myles/ViaVersion/api/protocol/ProtocolRegistry.java
- common/src/main/java/us/myles/ViaVersion/api/protocol/ProtocolVersion.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_11to1_10/BlockEntityRewriter.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_11to1_10/EntityIdRewriter.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_11to1_10/storage/EntityTracker.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_12to1_11_1/storage/EntityTracker.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/data/EntityNameRewriter.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/providers/BlockEntityProvider.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/providers/PaintingProvider.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/storage/EntityTracker.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_9_3to1_9_1_2/chunks/FakeTileEntity.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/ItemRewriter.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/metadata/MetaIndex.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/packets/EntityPackets.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/packets/SpawnPackets.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/sounds/SoundEffect.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/storage/CommandBlockStorage.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/storage/EntityTracker.java
- common/src/main/java/us/myles/ViaVersion/util/Config.java
Cleaned up the easy double checks, tested it on a lobbyserver (1.8 with 1.8-1.13 support) with about 50 players and looked over it a second and third time to make sure I didn't negate any if-clauses
>  Remove some more unncessary/doubled map check

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/Protocol1_13To1_12_2.java
Fixes color changing mid line in scoreboards in 1.13 and above
Before:
After:
> Fix scoreboard colors

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_9_1_2to1_9_3_4/types/Chunk1_9_3_4Type.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/types/Chunk1_9to1_8Type.java
> Fix chunk writing

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/Protocol1_13To1_12_2.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/data/RecipeData.java
- common/src/main/resources/assets/viaversion/data/itemrecipes1_12_2to1_13.json
> Recipe book

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/blockconnections/AbstractFenceConnectionHandler.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/blockconnections/WallConnectionHandler.java
I also removed waterlogged blocks from the ~~stair~~ fence data map.
> fix fence connections to stairs

- common/src/main/java/us/myles/ViaVersion/api/entities/Entity1_14Types.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_14to1_13_2/data/EntityTypeRewriter.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_14to1_13_2/packets/EntityPackets.java
> remove 1.14 object type (Mojang removed objcet trype in 19w05a)

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_14to1_13_2/Protocol1_14To1_13_2.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_14to1_13_2/packets/EntityPackets.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_14to1_13_2/packets/InventoryPackets.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_14to1_13_2/storage/EntityTracker.java
> Resync the inventory when selecting trade

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_14to1_13_2/MetadataRewriter.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_14to1_13_2/packets/WorldPackets.java
also made some if statements to if-else-...
> Remap areaeffectcloud particles

- bungee/src/main/java/us/myles/ViaVersion/bungee/handlers/BungeeEncodeHandler.java
- common/src/main/java/us/myles/ViaVersion/api/protocol/Protocol.java
- common/src/main/java/us/myles/ViaVersion/exception/CancelException.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/blockconnections/ConnectionData.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/packets/WorldPackets.java
- sponge/src/main/java/us/myles/ViaVersion/sponge/handlers/SpongeEncodeHandler.java
- velocity/src/main/java/us/myles/ViaVersion/velocity/handlers/VelocityEncodeHandler.java
> Workaround for packet order issue in neighbour chunk updates

- bukkit/src/main/java/us/myles/ViaVersion/bukkit/listeners/protocol1_9to1_8/PaperPatch.java
> Fix paperpatch

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_14_1to1_14/packets/EntityPackets.java
> fix missing final declaration

- common/src/main/java/us/myles/ViaVersion/api/type/types/version/ChunkSectionType1_13.java
- common/src/main/java/us/myles/ViaVersion/api/type/types/version/ChunkSectionType1_9.java
Fixes #1364
I have a replay file containing (at least) one affected chunk packet. ViaVersion fails to read it without this fix: http://paste.cytooxien.de/ojuputosin.makefile
With this fix all chunks can be read perfectly.
I also added a check that will throw an exception if the expected size (based on the given bitsPerBlock value) does not match the size of the read array. If there are more issues with reading chunks, this will make our lives a little bit easier :)
I also implemented the global palette in the ChunkSectionType1_9. 
I did not remove the check for bitsPerBlock values lower than 4 in this type, because there were no problems with it. However it might have to be removed too.
The client (at least 1.14.2) seems to not like chunk sections with bitsPerBlock < 4, so I kept the …
> fix 1.13 chunk reading, fix 1.9 chunk type not using global palette

- bukkit/pom.xml
- bungee/pom.xml
- common/pom.xml
- common/src/main/java/us/myles/ViaVersion/api/protocol/ProtocolVersion.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_14_4to1_14_3/Protocol1_14_4To1_14_3.java
- jar/pom.xml
- pom.xml
- sponge-legacy/pom.xml
- sponge/pom.xml
- velocity/pom.xml
_don't try to look at the fact I accidentally bumped the version with the first pre-release_
> 1.14.4-pre6 support

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_14to1_13_2/packets/WorldPackets.java
Should fix #1329, might need some testing to ensure there are no lighting bugs when the chunk is updated
> Fix 1.14 client lag on join

- bukkit/src/main/java/us/myles/ViaVersion/bukkit/listeners/multiversion/PlayerSneakListener.java
- bukkit/src/main/java/us/myles/ViaVersion/bukkit/platform/BukkitViaLoader.java
> Fix hitbox listener on 1.8.0 servers

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/packets/EntityPackets.java
see the comments in the code - should be good, but I still sent it to someone to test it
> Fix entity equipment packet for 1.9+ clients

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_11to1_10/Protocol1_11To1_10.java
Also made a little prettier by increments the id variable instead of having a separate one, so that the actual new sound ids can be checked for (instead of having to account for the otherwise created difference)
> Fix some sound rewrites

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_14_1to1_14/Protocol1_14_1To1_14.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_14_1to1_14/packets/EntityPackets.java
(also auto-replaced some tabs with whitespaces there)
> Untrack entities in 1.14.1 protocol

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_15to1_14_4/packets/EntityPackets.java
> Fix an error in the player spawn packet

- bukkit/pom.xml
- bungee/pom.xml
- common/pom.xml
- jar/pom.xml
- pom.xml
- sponge-legacy/pom.xml
- sponge/pom.xml
- velocity/pom.xml
... to prevent deployment/doubled versioning issues
> Bump version to 3.0.0-SNAPSHOT

- common/src/main/java/us/myles/ViaVersion/api/type/types/version/ChunkSectionType1_13.java
- common/src/main/java/us/myles/ViaVersion/api/type/types/version/ChunkSectionType1_9.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_14to1_13_2/packets/WorldPackets.java
- common/src/main/java/us/myles/ViaVersion/util/BiIntConsumer.java
- common/src/main/java/us/myles/ViaVersion/util/CompactArrayUtil.java
> deduplicate minecraft compact array code/decode

- common/src/main/java/us/myles/ViaVersion/api/minecraft/metadata/types/MetaType1_13.java
- common/src/main/java/us/myles/ViaVersion/api/minecraft/metadata/types/MetaType1_13_2.java
- common/src/main/java/us/myles/ViaVersion/api/minecraft/metadata/types/MetaType1_14.java
- common/src/main/java/us/myles/ViaVersion/api/type/Type.java
- common/src/main/java/us/myles/ViaVersion/api/type/types/Particle.java
- common/src/main/java/us/myles/ViaVersion/api/type/types/minecraft/Particle1_14Type.java
- common/src/main/java/us/myles/ViaVersion/api/type/types/version/Types1_13.java
- common/src/main/java/us/myles/ViaVersion/api/type/types/version/Types1_13_2.java
- common/src/main/java/us/myles/ViaVersion/api/type/types/version/Types1_14.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13_2to1_13_1/Protocol1_13_2To1_13_1.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13_2to1_13_1/types/Particle1_13_2Type.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/MetadataRewriter.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/Protocol1_13To1_12_2.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/data/ParticleRewriter.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/packets/WorldPackets.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/types/Particle1_13Type.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_14to1_13_2/MetadataRewriter.java
> Fix area effect cloud

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_15to1_14_4/Protocol1_15To1_14_4.java
> fix missing boss bar packet remap

- common/src/main/java/us/myles/ViaVersion/api/minecraft/chunks/Chunk.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_15to1_14_4/packets/WorldPackets.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_15to1_14_4/types/Chunk1_15Type.java
> Convert biome data to 1.15 format

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_15to1_14_4/Protocol1_15To1_14_4.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_15to1_14_4/packets/WorldPackets.java
> Fix acknowledge digging

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_15to1_14_4/packets/WorldPackets.java
Fixes #1573
Shouldn't normally happen, but eh
> Fix biomedata on some custom Spigot versions

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_15to1_14_4/Protocol1_15To1_14_4.java
> Fix book edit

- bukkit/pom.xml
- bungee/pom.xml
- bungee/src/main/java/us/myles/ViaVersion/bungee/platform/BungeeViaInjector.java
- common/pom.xml
- jar/pom.xml
- pom.xml
- sponge-legacy/pom.xml
- sponge/pom.xml
- velocity/pom.xml
_this is fine_
Thanks to the beautiful and only slightly fat CodeMatrix for helping me
> Fix Bungee injection on Java 12+

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_14to1_13_2/packets/WorldPackets.java
> Fix heightmaps

- common/src/main/java/us/myles/ViaVersion/api/entities/Entity1_11Types.java
> Fix 1.11 evocation id

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/Protocol1_13To1_12_2.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/data/StatisticMappings.java
Left out the item, block, and entity stats, since they'd require some _extra_ special treatment with considerably more caching (so I don't think it's actually worth doing so)
> Convert (general) 1.12.2->1.13 statistics

- bukkit/src/main/java/us/myles/ViaVersion/bukkit/platform/BukkitViaConfig.java
- bungee/src/main/java/us/myles/ViaVersion/bungee/platform/BungeeViaConfig.java
- common/src/main/java/us/myles/ViaVersion/api/ViaVersionConfig.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/data/MappingData.java
- common/src/main/resources/assets/viaversion/config.yml
- sponge/src/main/java/us/myles/ViaVersion/sponge/platform/SpongeViaConfig.java
- velocity/src/main/java/us/myles/ViaVersion/velocity/platform/VelocityViaConfig.java
> Option to (not) remap infested blocks to their normal variants

- bukkit/src/main/java/us/myles/ViaVersion/bukkit/platform/BukkitViaLoader.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/blockconnections/AbstractFenceConnectionHandler.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/blockconnections/AbstractStempConnectionHandler.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/blockconnections/BlockData.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/blockconnections/ChestConnectionHandler.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/blockconnections/ChorusPlantConnectionHandler.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/blockconnections/ConnectionData.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/blockconnections/ConnectionHandler.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/blockconnections/DoorConnectionHandler.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/blockconnections/FlowerConnectionHandler.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/blockconnections/GlassConnectionHandler.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/blockconnections/RedstoneConnectionHandler.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/blockconnections/SnowyGrassConnectionHandler.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/blockconnections/StairConnectionHandler.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/blockconnections/TripwireConnectionHandler.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/blockconnections/WrappedBlockData.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/blockconnections/providers/BlockConnectionProvider.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/packets/WorldPackets.java
Mostly just a few added finals and usages of lambdas, else some reduced map lookups in a handful of places
> Minor blockconnection cleanup, reduce map lookups

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_11to1_10/EntityIdRewriter.java
Removes some doubled lookups, also makes room for usage in VB
> Improvements to 1.11 EntityIdRewriter

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13_1to1_13/Protocol1_13_1To1_13.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13_1to1_13/packets/InventoryPackets.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13_2to1_13_1/packets/InventoryPackets.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/Protocol1_13To1_12_2.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_14to1_13_2/Protocol1_14To1_13_2.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_14to1_13_2/packets/InventoryPackets.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_15to1_14_4/Protocol1_15To1_14_4.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_15to1_14_4/packets/InventoryPackets.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_16to1_15_2/packets/InventoryPackets.java
> Handle items in cooldown packet

- bungee/src/main/java/us/myles/ViaVersion/bungee/storage/BungeeStorage.java
- common/src/main/java/us/myles/ViaVersion/api/ViaListener.java
- common/src/main/java/us/myles/ViaVersion/api/data/StoredObject.java
- common/src/main/java/us/myles/ViaVersion/api/data/UserConnection.java
- common/src/main/java/us/myles/ViaVersion/api/minecraft/chunks/ChunkSection.java
- common/src/main/java/us/myles/ViaVersion/api/minecraft/metadata/Metadata.java
- common/src/main/java/us/myles/ViaVersion/api/protocol/Protocol.java
- common/src/main/java/us/myles/ViaVersion/api/protocol/ProtocolVersion.java
- common/src/main/java/us/myles/ViaVersion/api/remapper/ValueTransformer.java
- common/src/main/java/us/myles/ViaVersion/api/type/Type.java
- common/src/main/java/us/myles/ViaVersion/api/type/types/Particle.java
- common/src/main/java/us/myles/ViaVersion/api/type/types/version/Types1_13.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_15to1_14_4/packets/EntityPackets.java
- velocity/src/main/java/us/myles/ViaVersion/velocity/storage/VelocityStorage.java
> Remove some lombok usage from the api package

- common/src/main/java/us/myles/ViaVersion/protocols/base/BaseProtocol1_7.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_16to1_15_2/packets/WorldPackets.java
Works™️, open for better solutions (if there are any) :>
Edit: For larger changes a new baseprotocol should be done, but I'd argue for this small of a thing, this check if fine
> Fix login packet reading on 1.16 servers, fix uuid nbt tags

- common/src/main/java/us/myles/ViaVersion/commands/defaultsubs/DumpSubCmd.java
- common/src/main/java/us/myles/ViaVersion/dump/VersionInfo.java
- jar/pom.xml
Writes an implementation version into the manifest, then also put into dumps (i.e. `Implementation-Version: git-ViaVersion-3.0.0-SNAPSHOT:d9291e6`)
> Add git commit hash to dumps

- common/src/main/java/us/myles/ViaVersion/ViaManager.java
- common/src/main/java/us/myles/ViaVersion/commands/defaultsubs/DumpSubCmd.java
- common/src/main/java/us/myles/ViaVersion/dump/VersionInfo.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_16to1_15_2/packets/InventoryPackets.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_16to1_15_2/packets/WorldPackets.java
> Add safety checks to skullowner conversion

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_12to1_11_1/Protocol1_12To1_11_1.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/Protocol1_13To1_12_2.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/blockconnections/ConnectionData.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/blockconnections/FireConnectionHandler.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_16to1_15_2/Protocol1_16To1_15_2.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/packets/PlayerPackets.java
- common/src/main/java/us/myles/ViaVersion/util/GsonUtil.java
Not perfect (doesn't cover all quirks), but would blow a bit out of proportion otherwise for now
> Add fire connection handler

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/Protocol1_13To1_12_2.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/packets/WorldPackets.java
> Fix block connections causing issues with TNT

- common/src/main/java/us/myles/ViaVersion/api/rewriters/SoundRewriter.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_11to1_10/Protocol1_11To1_10.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_12to1_11_1/Protocol1_12To1_11_1.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/Protocol1_13To1_12_2.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_14to1_13_2/Protocol1_14To1_13_2.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_15to1_14_4/Protocol1_15To1_14_4.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_16to1_15_2/Protocol1_16To1_15_2.java
VB can also nicely extend the soundrewriter
> Sound rewriter cleanup - don't send -1 sound ids

- common/src/main/java/us/myles/ViaVersion/api/protocol/ProtocolRegistry.java
- common/src/main/java/us/myles/ViaVersion/protocols/base/BaseProtocol1_16.java
- common/src/main/java/us/myles/ViaVersion/protocols/base/BaseProtocol1_7.java
Moved the version hack outside of the BaseProtocol class into separate impls with properly checking the sent version
> Fix 1.16 Bungee compat

- common/src/main/java/us/myles/ViaVersion/ViaManager.java
- common/src/main/java/us/myles/ViaVersion/api/boss/BossBar.java
- common/src/main/java/us/myles/ViaVersion/api/platform/ViaConnectionManager.java
- common/src/main/java/us/myles/ViaVersion/boss/CommonBoss.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/storage/EntityTracker1_9.java
may fix ViaVersion/VIaFabric#27
not tested.
> dont use uuids for bossbars, use userconnection

- common/src/main/java/us/myles/ViaVersion/boss/CommonBoss.java
should fix ViaVersion/ViaFabric#29
> Fix bossbar

- common/src/main/java/us/myles/ViaVersion/api/minecraft/nbt/BinaryTagIO.java
- common/src/main/java/us/myles/ViaVersion/api/minecraft/nbt/CharBuffer.java
- common/src/main/java/us/myles/ViaVersion/api/minecraft/nbt/StringTagParseException.java
- common/src/main/java/us/myles/ViaVersion/api/minecraft/nbt/TagStringReader.java
- common/src/main/java/us/myles/ViaVersion/api/minecraft/nbt/TagStringWriter.java
- common/src/main/java/us/myles/ViaVersion/api/minecraft/nbt/Tokens.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/ChatRewriter.java
> Fix 1.12->1.13 show_item handling

- .github/ISSUE_TEMPLATE/config.yml
Say goodby to incomplete issues with just one pastebin link...
> Disable blank issues ;)

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_11to1_10/Protocol1_11To1_10.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_11to1_10/data/PotionColorMapping.java
> fixed 1.11 -> 1.10.2 potion data remapping

- common/src/main/java/us/myles/ViaVersion/ViaManager.java
Link to ViaSetup if Via doesn't have any compatible versions for the server
> Link to ViaSetup

- LICENSE
Ok, here we go. The license bumped to 2020.
Disregard my other pull request, for some reason, I couldn't choose the correct branches. 🤔
> Update LICENSE to 2020

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_12to1_11_1/TranslateRewriter.java
This PR fixes the 1.11.1 -> 1.12 translation of show_achievement. Tested on 1.8, 1.9.4, 1.10.2, 1.11.2 server.
> fixed 1.11.1 -> 1.12 show_achievement translation

- common/src/main/java/us/myles/ViaVersion/api/protocol/ProtocolVersion.java
- common/src/main/java/us/myles/ViaVersion/api/protocol/VersionRange.java
- common/src/test/java/us/myles/ViaVersion/common/protocol/ProtocolVersionTest.java
> Improve ProtocolVersion subversion/range handling

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_16_2to1_16_1/packets/WorldPackets.java
Re-using the same workaround as #1302.
> fix 1.16.2 multi block change packet order

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_10to1_9_3/Protocol1_10To1_9_3_4.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_10to1_9_3/packets/InventoryPackets.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_11_1to1_11/Protocol1_11_1To1_11.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_11_1to1_11/packets/InventoryPackets.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_11to1_10/packets/InventoryPackets.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_12to1_11_1/packets/InventoryPackets.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/ItemRewriter.java
solve #2167 issue 
This is the first time i get into ViaVersion internals to contribute, i don't know if I did things like you want it to be.
> prevent 1.12- clients to creative-pick server-side unknown block/item

- common/src/main/java/us/myles/ViaVersion/api/PacketWrapper.java
Reduce useless transfert operation between these two lists.
discussed on Discord: https://discord.com/channels/316206679014244363/316208160232701955/782643199029280778
> Reduce useless List transfert operation

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/Protocol1_13To1_12_2.java
See https://github.com/cuberite/cuberite/issues/5074#issuecomment-742887124
> Add missing length check in 1.13 -> 1.12.2 stats code

- common/src/main/java/us/myles/ViaVersion/exception/InformativeException.java
Maybe people then use the template instead of just  replacing it with the error message
> Change error message for GitHub issues

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_14to1_13_2/packets/InventoryPackets.java
> [1.14 -> 1.13.2] Fix handling of unknown container ids

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_17to1_16_4/Protocol1_17To1_16_4.java
> Fix 21w08a+ Explosion Mapping

- common/src/main/java/us/myles/ViaVersion/AbstractViaConfig.java
- common/src/main/java/us/myles/ViaVersion/api/ViaVersionConfig.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_17to1_16_4/Protocol1_17To1_16_4.java
- common/src/main/resources/assets/viaversion/config.yml
_(I'm sorry for opening the pull request so often. 😢)_
This option will be of great help for servers that require the use of server resource pack. _(FPS, mini game, etc...)_
> Add "forced-use-1_17-resource-pack" option

- buildSrc/src/main/kotlin/Versions.kt
- common/build.gradle.kts
- common/src/main/java/us/myles/ViaVersion/api/minecraft/nbt/BinaryTagIO.java
- common/src/main/java/us/myles/ViaVersion/api/minecraft/nbt/TagStringReader.java
- common/src/main/java/us/myles/ViaVersion/api/minecraft/nbt/TagStringWriter.java
- common/src/main/java/us/myles/ViaVersion/api/type/types/minecraft/NBTType.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_12to1_11_1/Protocol1_12To1_11_1.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/data/ComponentRewriter1_13.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/packets/InventoryPackets.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/packets/WorldPackets.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/providers/blockentities/BannerHandler.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/providers/blockentities/BedHandler.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/providers/blockentities/SkullHandler.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_14to1_13_2/packets/InventoryPackets.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_14to1_13_2/packets/WorldPackets.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_16_2to1_16_1/data/MappingData.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_16to1_15_2/packets/EntityPackets.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_16to1_15_2/packets/InventoryPackets.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_16to1_15_2/packets/WorldPackets.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_17to1_16_4/packets/WorldPackets.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_9_1_2to1_9_3_4/chunks/BlockEntity.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_9_3to1_9_1_2/Protocol1_9_3To1_9_1_2.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_9_3to1_9_1_2/chunks/FakeTileEntity.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/ItemRewriter.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/packets/WorldPackets.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/storage/CommandBlockStorage.java
See https://github.com/ViaVersion/OpenNBT/commit/104486c6e192963bb03d2b3f77687eeba39a167e
> NBT lib improvements

- api/src/main/java/us/myles/ViaVersion/api/PacketWrapper.java
- api/src/main/java/us/myles/ViaVersion/api/data/UserConnection.java
- api/src/main/java/us/myles/ViaVersion/api/type/Type.java
- api/src/main/java/us/myles/ViaVersion/api/type/types/ShortByteArrayType.java
related to https://github.com/ViaVersion/ViaRewind/issues/219
> Add ShortByteArrayType, minor PacketWrapper changes

- api/src/main/java/com/viaversion/viaversion/api/configuration/ViaVersionConfig.java
- common/src/main/java/com/viaversion/viaversion/configuration/AbstractViaConfig.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_17to1_16_4/Protocol1_17To1_16_4.java
- common/src/main/java/com/viaversion/viaversion/util/Config.java
- common/src/main/resources/assets/viaversion/config.yml
This PR can set the resource pack prompt message.
It will be useful for servers that require resource packs with the "force-use-1_17-resource-pack" option.
I've tried to write a neat code, but I don't think it's neat.
Feedback on this PR is welcome.
> Add Resource pack prompt message option (1.17+)

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_9to1_8/Protocol1_9To1_8.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_9to1_8/packets/PlayerPackets.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_9to1_8/providers/CompressionProvider.java
> try to fix GoLilyPad servers

- api/src/main/java/com/viaversion/viaversion/api/configuration/ViaVersionConfig.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/WorldIdentifiers.java
- common/src/main/java/com/viaversion/viaversion/configuration/AbstractViaConfig.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_16to1_15_2/packets/EntityPackets.java
- common/src/main/resources/assets/viaversion/config.yml
This applies for 1.15 or below servers with 1.16 or above clients.
I'm contributing with the hopes that [Shotbow](https://shotbow.net/) will use it - their developers have expressed interest in their discord.
> Add support for setting a custom world name

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_14to1_13_2/packets/PlayerPackets.java
Fixes #2660 
Clients versions between 1.14 and 1.16 doesn’t add the `pages` key in the NBT tag when signing a empty book, which causes a kick for `Invalid book data!`. To fix this issue, this just adds an empty page to the book NBT tag, to reproduce the same behavior as other versions.
> Prevent kick when signing empty book

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_9to1_8/storage/EntityTracker1_9.java
> translatable ender dragon/wither text

- bungee/src/main/java/com/viaversion/viaversion/bungee/handlers/BungeeServerHandler.java
fixes #2730
Tested, seems to work fine.
This change remove support for BungeeCord builds prior to https://github.com/SpigotMC/BungeeCord/commit/c7b0c3cd48c9929c6ba41ff333727adba89b4e07 should I also make it work with older builds ?
> Update BungeeCord support

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_19to1_18_2/Protocol1_19To1_18_2.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_19to1_18_2/packets/EntityPackets.java
Before: https://i.imgur.com/7tc2O4Q.png
After: https://i.imgur.com/biQTTvx.png
> Actually make every message a system message

- api/src/main/java/com/viaversion/viaversion/api/protocol/version/ProtocolVersion.java
- gradle.properties
> Upate for 1.19-rc2

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_19to1_18_2/packets/EntityPackets.java
workaround for ViaVersion/ViaFabric#182 and #2915
> Use most similar dimension when it's not found

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13to1_12_2/blockconnections/providers/BlockConnectionProvider.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13to1_12_2/blockconnections/providers/PacketBlockConnectionProvider.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13to1_12_2/packets/WorldPackets.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13to1_12_2/storage/BlockConnectionStorage.java
> fix block connection on non-full chunks

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_16to1_15_2/Protocol1_16To1_15_2.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_16to1_15_2/packets/InventoryPackets.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_16to1_15_2/packets/WorldPackets.java
> Rewrite signs and books components on 1.16

- common/src/main/java/com/viaversion/viaversion/util/Config.java
> 1.15.2 Spigot/Paper NoSuchMethodError YamlCompat fix

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_19_4to1_19_3/Protocol1_19_4To1_19_3.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_19_4to1_19_3/packets/EntityPackets.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_19_4to1_19_3/storage/PlayerVehicleTracker.java
Fixes that the player is not dismounted when the server sets the boolean to true
> Properly handle dismount in PLAYER_POSITION packet

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_19_4to1_19_3/packets/EntityPackets.java
Allows the client player to be teleported by ENTITY_TELEPORT packets
> Handle ENTITY_TELEPORT's targeting the client player

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13to1_12_2/Protocol1_13To1_12_2.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13to1_12_2/providers/PlayerLookTargetProvider.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13to1_12_2/storage/TabCompleteTracker.java
This allows you to specify a player look target for 1.12- command completion if you have access to it.
> Add PlayerLookTargetProvider

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_16to1_15_2/packets/EntityPackets.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_16to1_15_2/packets/InventoryPackets.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_16to1_15_2/storage/InventoryTracker1_16.java
This pull request changes the InventoryTracker16 to use only a boolean for tracking, this is cleaner because the window id itself is never needed, also it fixes the issue that when using ViaVersion on the client the server can use negative window IDs to detect ViaVersion.
> Improved InventoryTracker16 Code

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_19_4to1_19_3/packets/InventoryPackets.java
> Let records properly stop in 1.19.3 -> 1.19.4

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_16to1_15_2/Protocol1_16To1_15_2.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_16to1_15_2/provider/PlayerAbilitiesProvider.java
This pull request adds a new provider for the player abilities in the 1.16 -> 1.15.2 protocol.
> Add PlayerAbilities Provider

- common/src/main/resources/assets/viaversion/config.yml
Updates the wiki.vg source to use HTTPS instead of HTTP in viaversion config file.
*(and that's literally it lol)*
> Use https instead of http for wiki.vg source.

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_20to1_19_4/packets/InventoryPackets.java
This is the same as vanilla behavior.
Tested on 1.12.2, 1.18.2, 1.19.4 and 1.20.1 server
Fixes #3433
> Fix sign nbt on 1.20.2 client

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_20_2to1_20/Protocol1_20_2To1_20.java
Fixes custom payloads properly
> Fixed 1.20.2 -> 1.20.1 brand custom payloads properly

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_19to1_18_2/provider/AckSequenceProvider.java
Reduces the delay between the player placing a block and the sequence being acknowledged to reduce the overall perceived delay on implementations where the ping is near 0 (ViaFabric)
> Reduced delay for sequence acknowledgements

- common/src/main/java/com/viaversion/viaversion/rewriter/EntityRewriter.java
Fixes a bug where entities whose metadata produces errors that should only be logged produce an IndexOutOfBoundsException.
The error comes from an attempted micro-optimization using an index that:
* goes to -1 on second metadata error (thus the out of bounds)
* is invalid as calls within the loop may add/remove elements to the list making index-based removal undefined behavior
> Fix disconnecting error for unknown mobs with metadata

- api/src/main/java/com/viaversion/viaversion/api/minecraft/signature/model/DecoratableMessage.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/signature/model/MessageMetadata.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/signature/model/chain/v1_19_1/MessageBody.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/signature/model/chain/v1_19_1/MessageHeader.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/signature/model/chain/v1_19_3/MessageBody.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/signature/model/chain/v1_19_3/MessageLink.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/signature/storage/ChatSession.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/signature/storage/ChatSession1_19_0.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/signature/storage/ChatSession1_19_1.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/signature/storage/ChatSession1_19_3.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/signature/util/DataConsumer.java
- api/src/main/java/com/viaversion/viaversion/util/GsonUtil.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_19_1to1_19/Protocol1_19_1To1_19.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_19_3to1_19_1/Protocol1_19_3To1_19_1.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_19_3to1_19_1/storage/NonceStorage.java
Allows newer clients to chat on older servers which enforce signed chat. Also allows joining onto servers which require a secure game profile. Needs the client's private signing key. To use this one needs to put the ChatSession_X classes into a UserConnection before the login process.
> Implemented support for chat signing

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13_1to1_13/packets/InventoryPackets.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13_2to1_13_1/packets/InventoryPackets.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_14to1_13_2/packets/InventoryPackets.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_16to1_15_2/Protocol1_16To1_15_2.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_20_2to1_20/Protocol1_20_2To1_20.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_9to1_8/packets/PlayerPackets.java
Fixes an edge case where too much data in a custom payload causes the client to disconnect.
Also handles channel identifiers properly by ensuring they are namespaced.
> Fixed and improved custom payload handling

- api/src/main/java/com/viaversion/viaversion/api/type/types/chunk/ChunkType1_13.java
- api/src/main/java/com/viaversion/viaversion/api/type/types/chunk/ChunkType1_14.java
- api/src/main/java/com/viaversion/viaversion/api/type/types/chunk/ChunkType1_15.java
- api/src/main/java/com/viaversion/viaversion/api/type/types/chunk/ChunkType1_16.java
- api/src/main/java/com/viaversion/viaversion/api/type/types/chunk/ChunkType1_16_2.java
- api/src/main/java/com/viaversion/viaversion/api/type/types/chunk/ChunkType1_17.java
- api/src/main/java/com/viaversion/viaversion/api/type/types/chunk/ChunkType1_18.java
- api/src/main/java/com/viaversion/viaversion/api/type/types/chunk/ChunkType1_9_1.java
- api/src/main/java/com/viaversion/viaversion/api/type/types/chunk/ChunkType1_9_3.java
Better solution for https://github.com/ViaVersion/ViaVersion/issues/681
> Fixed chunks not working in 1.9.1 -> 1.9

- api/src/main/java/com/viaversion/viaversion/api/minecraft/signature/SignableCommandArgumentsProvider.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_19_1to1_19/Protocol1_19_1To1_19.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_19_3to1_19_1/Protocol1_19_3To1_19_1.java
Allows platforms like ViaFabricPlus, ViaFabric and ViaForge to support signed command arguments.
> Implement provider to allow signed commands in 1.19.x protocols

- bukkit/src/main/resources/plugin.yml
- bungee/src/main/java/com/viaversion/viaversion/bungee/commands/BungeeCommand.java
- common/src/main/java/com/viaversion/viaversion/commands/ViaCommandHandler.java
- sponge/src/main/java/com/viaversion/viaversion/sponge/commands/SpongeCommandHandler.java
- velocity/src/main/java/com/viaversion/viaversion/velocity/command/VelocityCommandHandler.java
> Remove permission requirements for root command

- common/src/main/java/com/viaversion/viaversion/update/UpdateUtil.java
Use our own site (with GH in the background) for update check, also adjusted cache/header settings to fit
> Use our own site for update check

- common/src/main/java/com/viaversion/viaversion/util/Config.java
Adds handling for invalid config data types and returns the default value if the config data type is not correct
> Handle invalid config data types

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13to1_12_2/data/ParticleRewriter.java
Depthsuspend and mycelium are identical in appearance and therefore mycelium is a much better replacement than underwater which has a different color.
> Change depthsuspend to mycelium in 1.13 -> 1.12.2

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_14to1_13_2/metadata/MetadataRewriter1_14To1_13_2.java
Closes https://github.com/ViaVersion/ViaFabricPlus/issues/331
> Fixed elytra not working with firework rockets in 1.14 -> 1.13.2

- common/src/main/java/com/viaversion/viaversion/configuration/AbstractViaConfig.java
- common/src/main/java/com/viaversion/viaversion/util/Config.java
Fixed https://github.com/ViaVersion/ViaProxy/issues/179
> Use correct logger for configuration warnings

- api/src/main/java/com/viaversion/viaversion/api/protocol/version/ProtocolVersion.java
We need this for ViaFabricPlus
> Added between methods in ProtocolVersion

- api-legacy/src/main/java/us/myles/ViaVersion/api/protocol/ProtocolVersion.java
- api/src/main/java/com/viaversion/viaversion/api/protocol/version/ProtocolVersion.java
- api/src/main/java/com/viaversion/viaversion/api/protocol/version/ProtocolVersionRange.java
- api/src/main/java/com/viaversion/viaversion/api/protocol/version/SubVersionRange.java
- common/src/test/java/com/viaversion/viaversion/common/protocol/ProtocolVersionTest.java
This PR adds a new ProtocolVersionRange API which can be used to define and compare a range/set of ProtocolVersions, I also renamed the existing VersionRange class file
> Added ProtocolVersionRange API

- api/src/main/java/com/viaversion/viaversion/api/protocol/version/ProtocolVersion.java
- bukkit/src/main/java/com/viaversion/viaversion/bukkit/listeners/multiversion/PlayerSneakListener.java
- bukkit/src/main/java/com/viaversion/viaversion/bukkit/platform/BukkitViaLoader.java
- bukkit/src/main/java/com/viaversion/viaversion/bukkit/providers/BukkitAckSequenceProvider.java
- bungee/src/main/java/com/viaversion/viaversion/bungee/handlers/BungeeServerHandler.java
- bungee/src/main/java/com/viaversion/viaversion/bungee/platform/BungeeViaLoader.java
- common/src/main/java/com/viaversion/viaversion/ViaManagerImpl.java
- common/src/main/java/com/viaversion/viaversion/protocols/base/BaseProtocol.java
- common/src/main/java/com/viaversion/viaversion/protocols/base/BaseProtocol1_7.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_12to1_11_1/Protocol1_12To1_11_1.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13to1_12_2/blockconnections/AbstractFenceConnectionHandler.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13to1_12_2/blockconnections/GlassConnectionHandler.java
- velocity/src/main/java/com/viaversion/viaversion/velocity/platform/VelocityViaLoader.java
This PR also adds the missing ProtocolVersion#equalTo method
> Renamed comparing methods in ProtocolVersion class file

- bukkit-legacy/src/main/java/com/viaversion/viaversion/bukkit/util/ProtocolSupportUtil.java
- bungee/src/main/java/com/viaversion/viaversion/bungee/platform/BungeeViaConfig.java
- common/src/main/java/com/viaversion/viaversion/configuration/AbstractViaConfig.java
- common/src/main/java/com/viaversion/viaversion/util/Config.java
- velocity/src/main/java/com/viaversion/viaversion/velocity/platform/VelocityViaConfig.java
> Some code cleanup

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_20_5to1_20_3/rewriter/EntityPacketRewriter1_20_5.java
Fixes the issue where the Portal cooldown always becomes 0.
> Fix wrong join game packet handling

- fabric/src/main/resources/fabric.mod.json
ViaVersion will only work with ViaFabric so we should require it.
> Tidy up fabric.mod.json file of fabric platform

- bukkit-legacy/src/main/java/com/viaversion/viaversion/bukkit/listeners/protocol1_9to1_8/ArmorListener.java
- bukkit-legacy/src/main/java/com/viaversion/viaversion/bukkit/listeners/protocol1_9to1_8/DeathListener.java
- bukkit-legacy/src/main/java/com/viaversion/viaversion/bukkit/util/ProtocolSupportUtil.java
- bukkit/src/main/java/com/viaversion/viaversion/bukkit/listeners/multiversion/PlayerSneakListener.java
- bukkit/src/main/java/com/viaversion/viaversion/bukkit/listeners/protocol1_15to1_14_4/EntityToggleGlideListener.java
- bukkit/src/main/java/com/viaversion/viaversion/bukkit/platform/BukkitViaInjector.java
- bukkit/src/main/java/com/viaversion/viaversion/bukkit/providers/BukkitInventoryQuickMoveProvider.java
- bukkit/src/main/java/com/viaversion/viaversion/bukkit/providers/BukkitViaMovementTransmitter.java
- bukkit/src/main/java/com/viaversion/viaversion/bukkit/tasks/protocol1_19to1_18_2/AckSequenceTask.java
- bungee/src/main/java/com/viaversion/viaversion/bungee/handlers/BungeeChannelInitializer.java
- bungee/src/main/java/com/viaversion/viaversion/bungee/handlers/BungeeServerHandler.java
- bungee/src/main/java/com/viaversion/viaversion/bungee/listeners/ElytraPatch.java
- bungee/src/main/java/com/viaversion/viaversion/bungee/providers/BungeeMainHandProvider.java
- bungee/src/main/java/com/viaversion/viaversion/bungee/providers/BungeeVersionProvider.java
- bungee/src/main/java/com/viaversion/viaversion/bungee/storage/BungeeStorage.java
- common/src/main/java/com/viaversion/viaversion/legacy/bossbar/CommonBoss.java
- common/src/main/java/com/viaversion/viaversion/protocols/base/BaseProtocol1_7.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_11to1_10/metadata/MetadataRewriter1_11To1_10.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_12to1_11_1/Protocol1_12To1_11_1.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13to1_12_2/Protocol1_13To1_12_2.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13to1_12_2/data/BlockIdData.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13to1_12_2/storage/TabCompleteTracker.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_9to1_8/packets/PlayerPackets.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_9to1_8/packets/SpawnPackets.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_9to1_8/storage/EntityTracker1_9.java
- common/src/main/java/com/viaversion/viaversion/update/UpdateUtil.java
- velocity/src/main/java/com/viaversion/viaversion/velocity/platform/VelocityViaInjector.java
- velocity/src/main/java/com/viaversion/viaversion/velocity/providers/VelocityVersionProvider.java
- velocity/src/main/java/com/viaversion/viaversion/velocity/service/ProtocolDetectorService.java
- velocity/src/main/java/com/viaversion/viaversion/velocity/storage/VelocityStorage.java
Added proper logging with error messages in most places so we can identify errors easier.
> Replaced printStackTrace usages with proper logging

- api/src/main/java/com/viaversion/viaversion/util/ChunkUtil.java
Added some useful methods for ViaLegacy and ViaBedrock
> Added more functionality to ChunkUtil

- api/src/main/java/com/viaversion/viaversion/api/data/MappingDataBase.java
- api/src/main/java/com/viaversion/viaversion/api/data/MappingDataLoader.java
- common/src/main/java/com/viaversion/viaversion/protocol/ProtocolManagerImpl.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13to1_12_2/blockconnections/ConnectionData.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13to1_12_2/data/MappingData.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_14to1_13_2/data/MappingData.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_16_2to1_16_1/data/MappingData.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_19_4to1_19_3/data/MappingData.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_19to1_18_2/data/MappingData.java
Allows platforms to create their own MappingDataLoader and to override the loading behaviour in MappingDataBase.
> Allow platforms to use the mapping system

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_9to1_8/metadata/MetaIndex.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_9to1_8/metadata/MetadataRewriter1_9To1_8.java
Doesn't contain any actual changes which would be relevant for gameplay but only renamings.
> Cleanup MetaIndex style and field names

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_12to1_11_1/rewriter/TranslateRewriter.java
> Fix 1.12->1.11.1 show_achievement rewriter

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_16to1_15_2/packets/InventoryPackets.java
Fixes an item desync between client and server
> Fix 1.16->1.15.2 item attribute uuid

- bukkit-legacy/src/main/java/com/viaversion/viaversion/bukkit/listeners/protocol1_9to1_8/DeathListener.java
Closes https://github.com/ViaVersion/ViaVersion/issues/3817
> Fix component writing in DeathListener for 1.8->1.9

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_9to1_8/Protocol1_9To1_8.java
Thought it would take much longer or wouldn't get fixed at all, but here we go https://github.com/Lenni0451/MCStructs/commit/9784ef3259989aebb0a571c8402944ac7f059d49
> Remove fix which got merged into MCStructs

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_20_5to1_20_3/rewriter/BlockItemPacketRewriter1_20_5.java
Closes https://github.com/ViaVersion/ViaFabricPlus/issues/405
> Add block entity ids in 1.20.3->.5 conversion

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_20_5to1_20_3/rewriter/StructuredDataConverter.java
> Expose StructuredDataConverter#removeBackupTag

- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_3to1_20_5/rewriter/StructuredDataConverter.java
Solve https://github.com/ViaVersion/ViaVersion/pull/3862#issuecomment-2119158862
Referenced: https://github.com/PaperMC/Paper/blob/7ac24a18940da12beb39a030113f6e459f348e2f/patches/server/0665-Hide-unnecessary-itemmeta-from-clients.patch#L113-L115
Test environment:
1.20.6 Server & 1.20.4 Client
1.20.6 Server & 1.16 Client
1.20.6 Server & 1.15.2 Client
1.20.4 Server & 1.20.6 Client
1.20.4 Server & 1.20.2 Client
1.20.4 Server & 1.16 Client
1.20.4 Server & 1.15.2 Client
> Fix 1.20.5->1.20.3 Unpaired Lodestone Compass

- common/src/main/java/com/viaversion/viaversion/protocols/v1_20to1_20_2/Protocol1_20To1_20_2.java
Reading of the channel shouldn't be soft failed as the game code only try catches content reading
> Only soft fail CUSTOM_PAYLOAD content reading in 1.20->1.20.2

- common/src/main/java/com/viaversion/viaversion/protocols/v1_13_2to1_14/rewriter/EntityPacketRewriter1_14.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_13_2to1_14/rewriter/ItemPacketRewriter1_14.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_17to1_17_1/Protocol1_17To1_17_1.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_3to1_20_5/rewriter/BlockItemPacketRewriter1_20_5.java
Uses new constructor without the data short in protocols where data doesn't exist
> Replace DataItem constructor usages

- build-logic/src/main/kotlin/via.base-conventions.gradle.kts
- bukkit/src/main/resources/plugin.yml
Matches ViaBackwards and ViaRewind
> Include website url in plugin.yml

- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_3to1_20_5/rewriter/BlockItemPacketRewriter1_20_5.java
Also removes the comment from the rewriter class since it got removed on the component rewriter too.
> Move firework flight length appending into VB protocol

- common/src/main/java/com/viaversion/viaversion/protocols/v1_8to1_9/Protocol1_8To1_9.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_8to1_9/provider/HandItemProvider.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_8to1_9/rewriter/WorldPacketRewriter1_9.java
Minecraft never does that, also making it (AT)Nullable
> Don't send empty items in 1.8->1.9 hand item provider

- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_3to1_20_5/rewriter/BlockItemPacketRewriter1_20_5.java
Closes https://github.com/ViaVersion/ViaVersion/issues/3929
> Add armor stand entity id to ENTITY_DATA in 1.20.3->.5

- common/src/main/java/com/viaversion/viaversion/commands/defaultsubs/DisplayLeaksSubCmd.java
Rewrite the command to allow setting the actual level like in ViaLoader
> Add ability to set detection level in /viaversion displayleaks

- common/src/main/java/com/viaversion/viaversion/commands/ViaCommandHandler.java
- common/src/main/java/com/viaversion/viaversion/commands/defaultsubs/PlayerSubCmd.java
- common/src/main/java/com/viaversion/viaversion/commands/defaultsubs/ViewSubCmd.java
Adding a command to get the version of a singleton player, I think this can be useful for debugging since the list commands tends to be unreadable on servers with lots of players.
> Add /viaversion player <name|*> command

- api/src/main/java/com/viaversion/viaversion/api/minecraft/GameMode.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_8to1_9/rewriter/PlayerPacketRewriter1_9.java
This fixes the issue #3944 that I opened
> Fix players crashing when logging into a 1.8 server on hardcore mode

- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_3to1_20_5/rewriter/BlockItemPacketRewriter1_20_5.java
I'm proxy-PR'ing this for @AJ-Ferguson.
This fixes item desyncs between the client and server.
> 1.20.5 -> 1.20.3: nullify empty tags

- common/src/test/java/com/viaversion/viaversion/common/dummy/TestInjector.java
- common/src/test/java/com/viaversion/viaversion/common/dummy/TestLoader.java
The current code throws errors because of mapping loading
> Fix DummyInitializer unit test to bootstrap without errors

- common/src/test/java/com/viaversion/viaversion/common/dummy/TestCommandHandler.java
For situations like https://github.com/ViaVersion/ViaVersion/pull/3937
> Add test command handler to DummyInitializer test

- bukkit/src/main/java/com/viaversion/viaversion/bukkit/platform/BukkitViaConfig.java
- common/src/main/java/com/viaversion/viaversion/configuration/AbstractViaConfig.java
- velocity/src/main/java/com/viaversion/viaversion/velocity/platform/VelocityViaConfig.java
Reduces the amount of code every platform as to implement to get rid of the settings again.
> Move bukkit-only settings into BukkitViaConfig

- common/src/main/java/com/viaversion/viaversion/ViaManagerImpl.java
Now links to the release which contains a guide on how to update.
> Update unsupported java version warning

- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_3to1_20_5/rewriter/StructuredDataConverter.java
Fixes shulker box tooltips not showing all items for 1.20.3 clients on 1.20.5+ servers. 
TODO find out if we should backup the Slot tag in VV as well (it seems the server resyncs it, but I'm not sure if there are cases were that breaks) for creative mode.
Closes https://github.com/ViaVersion/ViaBackwards/issues/803 
Closes https://github.com/ViaVersion/ViaVersion/issues/3903
> Handle slot inside CONTAINER tag in 1.20.3->1.20.5

- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_3to1_20_5/Protocol1_20_3To1_20_5.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_3to1_20_5/storage/AcknowledgedMessagesStorage.java
To translate between a 1.20.5 client and 1.20.3 server, command packets without a last seen update need to attach a spoofed last seen update. Currently, this assumes that all messages were acknowledged by the client - which is not always the case.
An easy reproduction case is to mute a player using the Social Interactions screen, let them chat, and then send a message. As ViaVersion produces its own acknowledgements, this now does not match with what the client produced and signed its messages with - so the signature will fail verification.
As an alternative, we always pass through the same acknowledgement bit set - and for 'spoofed' messages, we reuse the last one that we received. In the case of the chat ack packet with just an offset, we need to hold back the window by at least 20 …
> Fix: delay chat acknowledgements instead of spoofing for 1.20.3 / 1.20.5 translation

- api/src/main/java/com/viaversion/viaversion/api/configuration/ViaVersionConfig.java
- common/src/main/java/com/viaversion/viaversion/configuration/AbstractViaConfig.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_8to1_9/rewriter/EntityPacketRewriter1_9.java
- common/src/main/resources/assets/viaversion/config.yml
Follow-up PR to https://github.com/ViaVersion/ViaVersion/pull/4006 ; since the option works now correctly there is no reason to keep it.
> Remove minimize-cooldown config option

- api/src/main/java/com/viaversion/viaversion/api/configuration/ViaVersionConfig.java
- bukkit/src/main/java/com/viaversion/viaversion/bukkit/platform/BukkitViaLoader.java
- common/src/main/java/com/viaversion/viaversion/configuration/AbstractViaConfig.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_8to1_9/rewriter/WorldPacketRewriter1_9.java
- common/src/main/resources/assets/viaversion/config.yml
I want to fix this in VFP properly as some other sounds are missing this fix which would be hard to implement in VV.
> Add cancel-block-sounds option for 1.8->1.9 place/break fix

- common/src/main/java/com/viaversion/viaversion/protocols/v1_19_4to1_20/Protocol1_19_4To1_20.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_2to1_20_3/Protocol1_20_2To1_20_3.java
- common/src/main/java/com/viaversion/viaversion/rewriter/ComponentRewriter.java
See https://github.com/ViaVersion/ViaBackwards/pull/818
> [ci skip] Fix player combat packet value comments

- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_3to1_20_5/rewriter/StructuredDataConverter.java
No idea what we did their but these are blocks and not items lol
> Fix block predicate conversion in 1.20.3->1.20.5

- common/src/main/java/com/viaversion/viaversion/protocol/RedirectProtocolVersion.java
> Expose origin version in RedirectProtocolVersion

- universal/build.gradle.kts
Removes VFP as well and recommends ViaBackwards/ViaRewind on both platforms
> Remove ViaFabricPlus dependency

- common/src/main/java/com/viaversion/viaversion/protocols/v1_11_1to1_12/data/ChatItemRewriter.java
Fixes https://github.com/ViaVersion/ViaVersion/issues/4051
> Rewrite show_item in translation components in 1.11.1->1.12

- common/src/main/java/com/viaversion/viaversion/protocols/v1_20to1_20_2/rewriter/BlockItemPacketRewriter1_20_2.java
Removes a bunch of duplicated code and replaces it with the rewriter functions
> Cleanup 1.20->1.20.2 item and recipe rewriter

- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_3to1_20_5/rewriter/BlockItemPacketRewriter1_20_5.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_3to1_20_5/rewriter/EntityPacketRewriter1_20_5.java
Closes https://github.com/ViaVersion/ViaVersion/issues/4048 and also fixes horse armor not being visible after rejoining
> Fix horse/llama's armor/carpet not visible in 1.20.3->1.20.5

- .github/workflows/build.yml
- .github/workflows/publish.yml
1. Updates the Ubuntu distribution to 24.04,
2. Syncs #4079 to the publish script.
> Update Ubuntu, Change wrapper-validation in publish

- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_3to1_20_5/rewriter/ComponentRewriter1_20_5.java
Closes https://github.com/ViaVersion/ViaFabricPlus/issues/517
> Fix ComponentRewriter1_20_5#convertFood behaviour

- common/src/main/java/com/viaversion/viaversion/data/entity/EntityTrackerBase.java
Required API change for https://github.com/ViaVersion/ViaBackwards/pull/871
> Make EntityTrackerBase#entities protected

- common/src/main/java/com/viaversion/viaversion/protocols/v1_12_2to1_13/rewriter/ItemPacketRewriter1_13.java
Closes https://github.com/ViaVersion/ViaFabricPlus/issues/560
> Cleanup enchantment conversion in 1.12->1.13 to match vanilla

- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_3to1_20_5/rewriter/ComponentRewriter1_20_5.java
Closes https://github.com/ViaVersion/ViaFabricPlus/issues/572
> Fix holder set direct id conversion in 1.20.3->1.20.5 component rewriter

- fabric/src/main/resources/fabric.mod.json
As discussed in https://github.com/ViaVersion/ViaFabric/pull/378
> Update required ViaFabric version, don't require fabric-loader

- common/src/main/java/com/viaversion/viaversion/rewriter/ComponentRewriter.java
- common/src/main/java/com/viaversion/viaversion/rewriter/StructuredItemRewriter.java
Since it contains text components it also needs to be handled.
Closes https://github.com/ViaVersion/ViaVersion/issues/4144
> Handle WRITTEN_BOOK_CONTENT component in rewriters as well

- common/src/main/java/com/viaversion/viaversion/commands/defaultsubs/DumpSubCmd.java
Since VV also runs on clients or as standalone proxy where the command system is loaded as well
> Change description of dump sub command to be more generic

- common/src/main/java/com/viaversion/viaversion/protocols/v1_12_2to1_13/provider/blockentities/FlowerPotHandler.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_17_1to1_18/storage/ChunkLightStorage.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_8to1_9/rewriter/WorldPacketRewriter1_9.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_8to1_9/storage/ClientWorld1_9.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_8to1_9/storage/CommandBlockStorage.java
> Code cleanup

- common/src/main/java/com/viaversion/viaversion/configuration/AbstractViaConfig.java
- common/src/main/resources/assets/viaversion/config.yml
Changes the config option "fix-1_21-placement-rotation" to true by default in order to restore vanilla behavior.
> Changed "fix-1_21-placement-rotation" to true by default

- api/src/main/java/com/viaversion/viaversion/api/configuration/ViaVersionConfig.java
- common/src/main/java/com/viaversion/viaversion/configuration/AbstractViaConfig.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_3to1_20_5/rewriter/BlockItemPacketRewriter1_20_5.java
- common/src/main/resources/assets/viaversion/config.yml
Some people might want to disable it since it breaks the sword blocking animation for clients older than 1.21.4
> Add config option for 1.20.4->1.20.5 sword blocking fix

- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_3to1_20_5/rewriter/RecipeRewriter1_20_5.java
> Rewrite ingredient items in 1.20.5 recipe rewriter

- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_5to1_21/Protocol1_20_5To1_21.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_5to1_21/rewriter/BlockItemPacketRewriter1_21.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_5to1_21/rewriter/EntityPacketRewriter1_21.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_5to1_21/storage/PlayerPositionStorage.java
Seems to be better after talking with anti cheat developers
> Send full position update packet in 1.20.5->1.21 placement rotation fix

- .github/workflows/build.yml
- .github/workflows/publish.yml
- .github/workflows/update-gradle-wrapper.yml
Yoinked from [EnZaXD's BaseProject #26](https://github.com/FlorianMichael/BaseProject/pull/26).
> Do not persist credentials

- .github/workflows/build.yml
- .github/workflows/publish.yml
Replaces the old validator job with the Gradle setup job.
> wrapper-validation -> setup-gradle

- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_3to1_20_5/rewriter/BlockItemPacketRewriter1_20_5.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_21to1_21_2/Protocol1_21To1_21_2.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_21to1_21_2/rewriter/BlockItemPacketRewriter1_21_2.java
Doesn't matter but looks cleaner, also changes a comment which confused me while debugging another issue.
> Reuse sound rewriter instance in 1.21->1.21.2

- .github/workflows/build.yml
Works by checking for the ViaVersionDev/preview git
> Upload artifacts to GitHub on the dev repository

- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_3to1_20_5/rewriter/ComponentRewriter1_20_5.java
- common/src/main/java/com/viaversion/viaversion/rewriter/ComponentRewriter.java
Moves the value->contents transition for entities to the common rewriter class for VB and cleans up the ComponentRewriter1_20_5 class to use the new handleShowItem function
> Add ComponentRewriter#convertLegacyEntityContents, cleanup 1.20.5 rewriter

- api/src/main/java/com/viaversion/viaversion/api/minecraft/entities/EntityTypes1_10.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/entities/EntityTypes1_11.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/entities/EntityTypes1_12.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/entities/EntityTypes1_13.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/entities/EntityTypes1_8.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/entities/EntityTypes1_9.java
Since they use the data int, we have to try get() without taking it in as it will otherwise always fail.
> Fix tracking of falling blocks

- common/src/main/java/com/viaversion/viaversion/protocol/ProtocolRunnable.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_12_2to1_13/task/TabCompleteTask.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_8to1_9/task/IdlePacketTask.java
Used for tasks as they all need the same base code
> Add ProtocolRunnable internal API

- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_3to1_20_5/rewriter/ComponentRewriter1_20_5.java
Only relevant for VB though as VV will never put empty structured data through it.
> Fix handling of removed item components in 1.20.3->.5 component rewriter

- api/src/main/java/com/viaversion/viaversion/util/Key.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_21_4to1_21_5/rewriter/BlockItemPacketRewriter1_21_5.java
Related to https://github.com/ViaVersion/ViaBackwards/issues/980
See also https://github.com/ViaVersion/ViaBackwards/pull/984
> Fix advancement menu background keys

- api/src/main/java/com/viaversion/viaversion/api/minecraft/GameProfile.java
Adds several methods/constructors to make using the GameProfile class easier
> Add QoL API for GameProfile

- common/src/main/java/com/viaversion/viaversion/protocols/v1_21to1_21_2/rewriter/EntityPacketRewriter1_21_2.java
Closes https://github.com/ViaVersion/ViaVersion/issues/4508
> Don't always send player inputs on Fabric servers in 1.21->1.21.2

- common/src/main/java/com/viaversion/viaversion/protocols/v1_12_2to1_13/Protocol1_12_2To1_13.java
Fixes Tablist plugins on some servers breaking since the game profile name sent is used to determine the scoreboard team which name we rewrite in other packets, also adds missing component rewriter calls to the display names (Not that important given its only translation keys, but we are already here).
> Rewrite player & display name in player info packet in 1.12.2->1.13

- common/src/main/java/com/viaversion/viaversion/protocols/v1_17_1to1_18/rewriter/ComponentRewriter1_18.java
Fixes https://github.com/ViaVersion/ViaFabricPlus/issues/705
> Add missing biome name translations in 1.17.1->1.18

- api/src/main/java/com/viaversion/viaversion/api/protocol/packet/PacketTracker.java
Fixes plugins like Grim breaking on our changes since people don't expect breaking API changes in minor versions.
> Add some backwards compatibility functions to PacketTracker

- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_3to1_20_5/Protocol1_20_3To1_20_5.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_3to1_20_5/rewriter/EntityPacketRewriter1_20_5.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_3to1_20_5/storage/ScoreboardTeamStorage.java
Fixes bad plugins breaking newer clients due to sending of bad packets.
Closes https://github.com/ViaVersion/ViaVersion/issues/4564
> Filter invalid remove teams packets in 1.20.3->1.20.5
