ViaVersion/ViaVersion

- src/main/java/us/myles/ViaVersion/transformers/OutgoingTransformer.java
Tracking position boolean will be always true, but it works.
> Fix map crash

- pom.xml
How about we make this buildable across machines by actually using a maven repository to fetch the Bukkit dependency from
> Add Spigot's maven repo, so this is actually useful

- pom.xml
- src/main/resources/plugin.yml
> Fixed some maven warnings.

- src/main/java/us/myles/ViaVersion/ViaVersionPlugin.java
FIXED:
When starting the server when checkforupdates is false, it won't register the listener.
So when you enable checkforupdates using /viaversion dontbugme it won't send you messages until a restart.
> Fix checkforupdates changing from false to true

- src/main/java/us/myles/ViaVersion/transformers/IncomingTransformer.java
Fix exception on opening horses inventory / elytra 
[19:30:26] [Netty Server IO #0/WARN]: Caused by: java.lang.ArrayIndexOutOfBoundsException: 7
[19:30:26] [Netty Server IO #0/WARN]: 	at net.minecraft.server.v1_8_R3.PacketDataSerializer.a(PacketDataSerializer.java:73)
[19:30:26] [Netty Server IO #0/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInEntityAction.a(SourceFile:30)
[19:30:26] [Netty Server IO #0/WARN]: 	at net.minecraft.server.v1_8_R3.PacketDecoder.decode(SourceFile:40)
[19:30:26] [Netty Server IO #0/WARN]: 	... 37 more
> Fixed horses inventory/elytra exception

- src/main/java/us/myles/ViaVersion/ConnectionInfo.java
- src/main/java/us/myles/ViaVersion/ViaIdleThread.java
- src/main/java/us/myles/ViaVersion/ViaVersionPlugin.java
- src/main/java/us/myles/ViaVersion/handlers/ViaDecodeHandler.java
Manually performs idle updates by keeping track of the player's
movement.
It compensates for the missing idle packets attempting to get a ratio of
20 movement related packets per second.
> Manually perform idle updates. Fixed #160 #99

- src/main/java/us/myles/ViaVersion/metadata/MetaIndex.java
- src/main/java/us/myles/ViaVersion/metadata/MetadataRewriter.java
- src/main/java/us/myles/ViaVersion/transformers/OutgoingTransformer.java
Automatically converts legacy boss bars to 1.9 ones using ViaVersions's
boss API.
I suggest you add a config option
Note: also fixed crash on wither/dragon spawn
http://i.imgur.com/vh7mSlQ.png
> Add support for 1.8 boss bars. Fixes #41

- src/main/java/us/myles/ViaVersion/handlers/ViaChunkHandler.java
- src/main/java/us/myles/ViaVersion/handlers/ViaEncodeHandler.java
- src/main/java/us/myles/ViaVersion/handlers/ViaVersionInitializer.java
Split chunk bulk packet up in to single chunk packets before it reached the encoder.
This will prevent issues with several plugins and other protocol handlers due to the chunk being sent twice.
It also sends the chunk in the right order possible resolving some issues with added chunk/block/entity data.
> Add chunk handler to netty pipeline. Fixes #48

- src/main/java/us/myles/ViaVersion/listeners/CommandBlockListener.java
- src/main/java/us/myles/ViaVersion/transformers/OutgoingTransformer.java
- src/main/java/us/myles/ViaVersion/util/ReflectionUtil.java
In 1.8, the server sent PLAY_UPDATE_BLOCK_ENTITY every time some commandblock get's updated. But if you open a commandblock window, it wouldn't get updated
In 1.9, it only updates when you open it. The commandblock window get updated every time PLAY_UPDATE_BLOCK_ENTITY is sent. This would mean, if some commandblock somewhere changed. It would change your window to that. Even if it was not the commandblock you opened.
Before: https://fileserver.matsv.nl/media?id=0ea0808544239fb7debf084c226ac132
After: https://fileserver.matsv.nl/media?id=12c66ee1bcc30b2e53a4d7155028feb3
> Fix commandblocks not able to change command on update

- src/main/java/us/myles/ViaVersion/ViaVersionPlugin.java
- src/main/java/us/myles/ViaVersion/transformers/OutgoingTransformer.java
- src/main/resources/config.yml
Let users choose to use the new effect indicators in 1.9
This will not support the new beacon glowing effect
http://wiki.vg/Protocol#Entity_Effect
Particle byte enum has to be:
Type | Value
------------ | -------------
0 | Show particles
1 | Hide particles
2 | Show particles & Effect indicator (Used for potions)
3 | Hide particles & Effect indicator with glow (Used for beacons)
If someone wants to change/report that at wiki.vg. Please go ahead :)
> Make it possible to use the new effect indicators in 1.9

- src/main/java/us/myles/ViaVersion/metadata/MetaIndex.java
See #225 for more info.
In 1.8 you didn't got kicked for invalid metadata. Probably doesn't exists.
Might fix AAC anti killaura. Not tested. Don't own a copy of it.
> Discountinue player metadata 11.

- src/main/java/us/myles/ViaVersion/ViaVersionPlugin.java
- src/main/java/us/myles/ViaVersion/api/ViaVersionAPI.java
in 1.9.1 there will be another protocol id. So this might be useful for developers.
> Add api method to get player's protocol id

- src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/storage/EntityTracker.java
According to wiki.vg, this metadata only impacts the swing, but according to my research, it only impacts the bow, not 100% sure. But wither skeletons were still able to swing.
http://wiki.vg/Entities#Skeleton
> Show skeletons bow like 1.8, not down as 1.9 without target

- src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/types/ChunkType.java
You unload it here:
https://github.com/MylesIsCool/ViaVersion/blob/master/src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/types/ChunkType.java#L131-L134
And over here:
https://github.com/MylesIsCool/ViaVersion/blob/master/src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/packets/WorldPackets.java#L119-L125
That was not the case in 0.6.7
@gigosaurus Could you test if #338 still happens?
> Don't unload chunks twice

- src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/packets/InventoryPackets.java
If you opened the inventory with items in the slots, you'd see it twice, one real, one fake. probably won't fix #358 but it's a bug I found
> Fix brewing item showing twice, one in the new slot one in the old

- src/main/java/us/myles/ViaVersion/api/protocol/ProtocolRegistry.java
- src/main/java/us/myles/ViaVersion/api/protocol/ProtocolVersion.java
- src/main/java/us/myles/ViaVersion/protocols/protocol1_10to1_9_3/Protocol1_10To1_9_3_4.java
- src/main/java/us/myles/ViaVersion/protocols/protocol1_10to1_9_3/types/Meta1_10Type.java
- src/main/java/us/myles/ViaVersion/protocols/protocol1_10to1_9_3/types/MetaList1_10Type.java
Some classes and variable names are still "snapshot", so I've changed them to "1.10"
> Update names from 'snapshot' to '1.10'

- src/main/java/us/myles/ViaVersion/ViaConfig.java
- src/main/resources/config.yml
https://github.com/filoghost/HolographicDisplays/blob/master/HolographicDisplays/Plugin/com/gmail/filoghost/holographicdisplays/util/Offsets.java#L15 The offset is by default -1.25 for 1.8, however 1.9 clients require only -0.29. (-1.25 - -0.29) = -0.96 which should be the correct offset.
> Correct hologram Y offset

- src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/ItemRewriter.java
As I said on https://github.com/MylesIsCool/ViaVersion/issues/420
I've made this convertor when spigot 1.9 was released. I adapted it for ViaVersion.
This change will still use the existing potion data registration when available, so it will not cause any impact where it's already working.
> Fixes potion data conversion from 1.8 to 1.9

- README.md
buzz.spi.gt could be down at the time that someone clicks it.
(It is very unlikely)
(Anything can happen)
> dont use buzz.spi.gt only

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_11to1_10/ItemRewriter.java
This will change all items with negative or zero amount, so the 1.11 client can display them.
> Fixing item count on 1.11, where size <= 0. (#553)

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/packets/WorldPackets.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/storage/EntityTracker.java
This should fix a problem where the shield appears while players use a bow (switching to a bow quicky while holding a sword), or at least it reduces that possibility.
> Improved the shield handling (1.9->1.8)

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/ItemRewriter.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/packets/PlayerPackets.java
1.8 clients insert quotes at the start and end of an empty string. However 1.9+ clients no longer do that so we've to do it manually because the chat serializer doesn't like empty strings. 
Formating the book data correctly fixes #737 and spaces randomly disappearing before the first character of each page. (annoying when trying to position text on a [page](https://youtu.be/IdjW2KkMhVY).
Tested on a 1.8.8 spigot server with 1.9 and 1.12.2 clients.
> Format the book data correctly, fixes #737 + spaces

- bukkit/src/main/java/us/myles/ViaVersion/ViaVersionPlugin.java
- bukkit/src/main/java/us/myles/ViaVersion/bukkit/platform/BukkitConfigAPI.java
- bukkit/src/main/java/us/myles/ViaVersion/bukkit/platform/BukkitViaLoader.java
- bukkit/src/main/java/us/myles/ViaVersion/bukkit/protocol1_12to1_11_1/BukkitInvContainerUpdateTask.java
- bukkit/src/main/java/us/myles/ViaVersion/bukkit/providers/BukkitInvContainerItemProvider.java
- bukkit/src/main/java/us/myles/ViaVersion/bukkit/providers/BukkitInventoryQuickMoveProvider.java
- bukkit/src/main/java/us/myles/ViaVersion/bukkit/tasks/protocol1_12to1_11_1/BukkitInventoryUpdateTask.java
- bungee/src/main/java/us/myles/ViaVersion/BungeePlugin.java
- bungee/src/main/java/us/myles/ViaVersion/bungee/platform/BungeeConfigAPI.java
- common/src/main/java/us/myles/ViaVersion/api/ViaVersionConfig.java
- common/src/main/java/us/myles/ViaVersion/api/platform/ViaPlatform.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_12to1_11_1/Protocol1_12To1_11_1.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_12to1_11_1/packets/InventoryPackets.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_12to1_11_1/providers/InventoryQuickMoveProvider.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_12to1_11_1/storage/ItemTransaction.java
- common/src/main/resources/assets/viaversion/config.yml
- sponge/src/main/java/us/myles/ViaVersion/SpongePlugin.java
- sponge/src/main/java/us/myles/ViaVersion/sponge/platform/SpongeConfigAPI.java
This improves inventory handling and fixes #739 for **bukkit** servers.
1.12+ clients behave differently with the WindowClick packet when used with quick move action. 
http://wiki.vg/index.php?title=Protocol&oldid=13223#Click_Window
Previously clients grab the item from the clicked slot **before** it has been moved however now they grab the slot item **after** it has been moved and send that in the packet. 
Because of this the slot will always be empty so the sent item is null which doesn't make any sense.  
< 1.12 servers require the client to send the moved item and then the server will compare it to see if it equals with the item that the server has (to prevent abuse or something?). 
This isn't the case on 1.12+ servers due they no longer require the item being sent in the packet. So …
> Improve inventory handling for Bukkit servers

- common/src/main/java/us/myles/ViaVersion/protocols/protocolsnapshotto1_12_2/providers/PaintingProvider.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocolsnapshotto1_12_2/providers/blockentities/SkullHandler.java
Skulls on walls don't always have a 'Rot' tag if it's rotation is 0.
'DonkeyKong', 'SkullAndRoses' and 'BurningSkull' were displaying the default painting instead.
> Skulls don't have 'Rot'; Painting names

- bukkit/src/main/java/us/myles/ViaVersion/bukkit/platform/BukkitViaLoader.java
Apparently the bug that caused the block placement issues with Paper was fixed in 1.12 ([according to Aikar from its development team](https://vgy.me/r4Xyal.png)). So, with this ~~commit~~ PR the patch to fix it won't run if the server is running Paper 1.12 or higher (which means it will only be used in 1.11.2 and lower server versions).
> Don't use Paper block placement patch in 1.12.

- bukkit/src/main/java/us/myles/ViaVersion/bukkit/listeners/protocol1_9to1_8/HandItemCache.java
- sponge/src/main/java/us/myles/ViaVersion/sponge/listeners/protocol1_9to1_8/HandItemCache.java
These double checks can usually be simplified by removing the explicit check, as the contains check is nothing but a get() != null check.
... If accepted and plausable, I could also go over the other double checks
> Remove unncessary doubled map check

- common/src/main/java/us/myles/ViaVersion/api/minecraft/chunks/ChunkSection.java
- common/src/main/java/us/myles/ViaVersion/api/type/types/version/ChunkSectionType1_13.java
- common/src/main/java/us/myles/ViaVersion/api/type/types/version/ChunkSectionType1_8.java
- common/src/main/java/us/myles/ViaVersion/api/type/types/version/ChunkSectionType1_9.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13_1to1_13/packets/WorldPackets.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/packets/WorldPackets.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_14to1_13_2/packets/WorldPackets.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_9_3to1_9_1_2/types/Chunk1_9_1_2Type.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/types/Chunk1_9to1_8Type.java
Improves performance of the palette in the ChunkSection (when setting blocks).
I did run a simple test to see the performance difference.
`ChunkSection section = new ChunkSection();
long time;
time = System.nanoTime();
for (int i = 0; i < 10000; i++) {
section.setFlatBlock(0, 0, 0, i);
}
System.out.println(System.nanoTime() - time);
time = System.nanoTime();
for(int i = 0; i < 10000; i++) {
section.setFlatBlock(0, 0, 0, i % 10);
}
System.out.println(System.nanoTime() - time);`
Old palette:
59922433 (= 59.9ms)
2106559 (= 2.1ms)
New palette:
5519727 (= 5.5ms, 90.7% increase)
969519 (= 1.0ms, 54.0% increase)
> Faster palette

- bukkit/src/main/java/us/myles/ViaVersion/bukkit/platform/BukkitViaConfig.java
- bungee/src/main/java/us/myles/ViaVersion/bungee/platform/BungeeViaConfig.java
- common/src/main/java/us/myles/ViaVersion/api/ViaVersionConfig.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/blockconnections/FlowerConnectionHandler.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/data/MappingData.java
- common/src/main/resources/assets/viaversion/config.yml
- sponge/src/main/java/us/myles/ViaVersion/sponge/platform/SpongeViaConfig.java
- velocity/src/main/java/us/myles/ViaVersion/velocity/platform/VelocityViaConfig.java
Added two (false by default) config fields: The first option fixes the lack of collision of the 1-layer snow for 1.13 clients by replacing it as 2-layers for the client (before you could stand on a 1-layer snow even if there's no block below, which is used in custom builds as well as through some world generating failures in lower versions with flying snow, which means 1.13 clients will have a hard time walking above them).
The second option is just something "nice to have" and fixes custom decorative flower stems (used by many builders, at least in Germany).
Also changed the "1.9&1.10" lines in the config to "1.9+" and moved blockconnection to the matching config section
(Images for how the stems should actually look, else the top of the sunflower stems would be the actual sunflower top …
> Add fixes for custom flowerstems and snowcollision for 1.13 clients

- bukkit/src/main/java/us/myles/ViaVersion/bukkit/platform/BukkitViaConfig.java
- bungee/src/main/java/us/myles/ViaVersion/bungee/platform/BungeeViaConfig.java
- common/src/main/java/us/myles/ViaVersion/api/ViaVersionConfig.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_14to1_13_2/packets/InventoryPackets.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_14to1_13_2/packets/PlayerPackets.java
- common/src/main/resources/assets/viaversion/config.yml
- sponge/src/main/java/us/myles/ViaVersion/sponge/platform/SpongeViaConfig.java
- velocity/src/main/java/us/myles/ViaVersion/velocity/platform/VelocityViaConfig.java
When editing a book, the client can write up to 100 pages in 1.14 wheras it was 50 before.
Some anti-exploit plugins ban on that behalf (especially used on 1.8), so I figured an option to truncate that would be useful
> Add option to truncate edited books with more than 50 pages on 1.14

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/packets/InventoryPackets.java
Bukkit interprets this as attempting to register the channel "" (the empty string), which fails on Minecraft 1.13 and above.
> Don't try to send register messages without channels

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/packets/InventoryPackets.java
**The Issue**
On our 1.12.2 server we had a problem that clients which are playing on 1.13+ can't use a pickaxe with the 'CanDestroy' tag. This is I figured because of the pickaxe having a taglist of the materials written in full caps. The issue thus being that a client lower or equal to 1.12.2 does accept this tag, but a 1.13+ client doesn't because the client apparently wants a material written in lower caps.
This is a 1.12.2 client which can interact with blocks: 
https://gyazo.com/64880380560d9b5ff4756b549c1e7f26
This is a 1.13.2 client which can't interact with some blocks (the tag has STONE written in caps): 
https://gyazo.com/6ec22751ab10d75b3ece548b321cf7ae
**Why Should ViaVersion Have This Fix?**
Simply because some clients can use the pickaxe with the tag, and some can't. Thus …
> Issue with the CanDestroy taglist

- bungee/src/main/java/us/myles/ViaVersion/bungee/handlers/BungeeServerHandler.java
When a player connects to a child server on Bungeecord a ServerConnectEvent is executed. If this event is cancelled then the player will remain on their previous server.
ViaVersion does not check if the event is cancelled and sets the protocol level to that of the child server. This causes havoc if the original server is a different version and will throw a bewildering array of errors based upon what the player does NEXT. This had made it nearly impossible to track down.
Errors can vary widely and include Tabcomplete errors or an EntityRemap errors in Bungeecord as it suddenly gets very confusing data. The server owner then logs an issue against Bungeecord and @md-5 slowly goes mad.
* In BungeeServerHandler#onServerConnect check if the event is cancelled
```
java.lang.RuntimeException: …
```
> Fix ServerConnectEvent ignoring a cancelled event

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/packets/InventoryPackets.java
Some smart guy should prolly still verify this (tho it should be good: `+` = once or more, then there's a mandatory `:`, and another once or more for all lowercase alphanumerical thingies).
Before, the `?` allowed to emit the left identifier (which isn't possible in CB) and the`*` also marked a "0 or more"
Fixes https://github.com/ViaVersion/ViaBackwards/issues/138 and https://github.com/ViaVersion/ViaBackwards/issues/128
> Fix plugin message pattern

- bukkit/src/main/java/us/myles/ViaVersion/bukkit/platform/BukkitViaConfig.java
- bungee/src/main/java/us/myles/ViaVersion/bungee/platform/BungeeViaConfig.java
- common/src/main/java/us/myles/ViaVersion/api/ViaVersionConfig.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_14to1_13_2/MetadataRewriter.java
- common/src/main/resources/assets/viaversion/config.yml
- sponge/src/main/java/us/myles/ViaVersion/sponge/platform/SpongeViaConfig.java
- velocity/src/main/java/us/myles/ViaVersion/velocity/platform/VelocityViaConfig.java
The player walk animation will not be shown to a player using Minecraft 1.14 or later if the player has their health set to Float.NaN. Several anti damage-indicator plugins replace the players health with NaN before the metadata is sent to the other clients.
This PR fixes #1406 by replacing NaN health with a normal value if it was not disabled in the config. This change will only affect 1.14+ clients.
> Fix 1.14+ walk animation

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/Protocol1_13To1_12_2.java
Fix scoreboard colors for some plugins using non colors formatting like `§r` for players names (same as #1050 but with other color/formatting codes).
This should fix #1255, but I can’t test because the plugins are not public.
I tested with QuickBoard (wich use `§r`) - https://github.com/ViaVersion/ViaVersion/issues/1255#issuecomment-486296053 - and it works
Tests with QuickBoard v4.3.0, using 1.13.2 client on 1.8.8 server:
_Before:_
_After:_
> Fix scoreboard colors on 1.13

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_12to1_11_1/ChatItemRewriter.java
Fix item hover event on 1.12 when the `value` of the hover event is a string array and not a string, like this (from Item2Chat):
```
"hoverEvent": {
"action": "show_item",
"value": [
"{id:\"minecraft:diamond_sword\",Count:1b,tag:{ench:[0:{lvl:2s,id:19s}]},Damage:4s}"
]
}
```
Tests with [Item2Chat](https://www.spigotmc.org/resources/item2chat.33622/) v4.2.0 (fix #826, and should fix #799) using 1.12.2 client on 1.8.8 server:
Before
After
> Fix item hover event on 1.12

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/data/MappingData.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/data/StatisticMappings.java
(Doesn't result in false behaviour, but the correct distinction is needed for VB)
> Put translation values into correct map

- bukkit/src/main/java/us/myles/ViaVersion/bukkit/platform/BukkitViaConfig.java
- bungee/src/main/java/us/myles/ViaVersion/bungee/platform/BungeeViaConfig.java
- common/src/main/java/us/myles/ViaVersion/api/ViaVersionConfig.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/blockconnections/ConnectionData.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/blockconnections/VineConnectionHandler.java
- common/src/main/resources/assets/viaversion/config.yml
- sponge/src/main/java/us/myles/ViaVersion/sponge/platform/SpongeViaConfig.java
- velocity/src/main/java/us/myles/ViaVersion/velocity/platform/VelocityViaConfig.java
Works by only sending vines that are either:
a) attached to a block or
b) have another vine above them that is attached to a block
Fixes #1640
> Add vines blockconnection to prevent unwanted climbing

- sponge-legacy/pom.xml
- sponge/pom.xml
[![mitm_build](https://user-images.githubusercontent.com/1323708/59226671-90645200-8ba1-11e9-8ab3-39292bef99e9.jpeg)](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Update: Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/bugbountywriteup/update-want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-d069d253fe23?source=friends_link&sk=8c8e52a7d57b98d0b7e541665688b454)
---
This is a security fix for …
> [SECURITY] Use HTTPS to resolve dependencies in Maven Build

- common/src/main/java/us/myles/ViaVersion/api/minecraft/chunks/BaseChunk.java
- common/src/main/java/us/myles/ViaVersion/api/minecraft/chunks/Chunk.java
- common/src/main/java/us/myles/ViaVersion/api/minecraft/chunks/Chunk1_8.java
- common/src/main/java/us/myles/ViaVersion/api/minecraft/chunks/ChunkSection.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/types/Chunk1_13Type.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_14to1_13_2/packets/WorldPackets.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_14to1_13_2/types/Chunk1_14Type.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_15to1_14_4/packets/WorldPackets.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_15to1_14_4/types/Chunk1_15Type.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_9_1_2to1_9_3_4/types/Chunk1_9_3_4Type.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_9_3to1_9_1_2/types/Chunk1_9_1_2Type.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/types/Chunk1_9to1_8Type.java
Renamed groundUp to fullChunk to be less confusing and removed unnecessary bitset wrapping for one time uses only (probably got copy pasted from older chunks where they were more helpful)
> Minor chunk type cleanup

- common/src/main/java/us/myles/ViaVersion/ViaManager.java
- common/src/main/java/us/myles/ViaVersion/exception/InformativeException.java
- velocity/src/main/java/us/myles/ViaVersion/VelocityPlugin.java
Necessary for the proxies that don't have sync ticking, since the pre-init and full-init happen directly after one another without any option to intercept
> Add runnable list to be executed before the full init

- fabric/src/main/resources/fabric.mod.json
It's kinda of a library, but it has implementations too. I don't know how to categorize it
> Remove "API" from name in fabric.mod.json

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/ChatRewriter.java
This is the second PR where I've pulled changes from the private ViaVersion fork we use at Mineteria that is strongly focused on performance.
This PR removes the URL detection logic from the 1.13<->1.12.2 `ChatRewriter`. Since this is used in parts of the game where you can't interact with the text (unlike chat), this logic only serves to waste CPU time.
This provides a minor performance improvement for servers using pre-1.13 versions of Minecraft running ViaVersion.
> Remove useless URL detection and event addition from 1.13->1.12.2 ChatRewriter

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_12to1_11_1/ChatItemRewriter.java
Having an NBT key such as `CrateKey-monthly_february_2020:` would become impossible to have as `2020:` would be matched and replaced. The purpose of this functionality is to replace indexes only. This adds a negative lookbehind to make sure the characters before the match are not that of characters for a valid key. This still allows it to be matched in all other cases, so while `CrateKey-monthly_february_2020:` would not be matched, however `[2020:` would, as well as `,2020` etc. Characters that would invalidate this from being matched are `A-Za-z_-.+`.
> Ensure normal keys that end with numbers don't get matched and replaced when replacing indexes

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_16to1_15_2/Protocol1_16To1_15_2.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_16to1_15_2/packets/InventoryPackets.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_16to1_15_2/storage/InventoryTracker1_16.java
On older versions of the server you could open an inventory with one already open and it would close the old one and open the new one. On 1.16 this does not appear to be the case and attempting to do this would result in both inventories closing. This broke all the inventory menus we had on Mineteria and caused similar issues on another larger server. As a result this change tracks the inventory ID that has been open and removes it when it has closed. An attempt to open an inventory while one is already open will make sure the previous inventory is closed first. This solved problems on both servers.
> Close the open inventory before opening a new one on 1.16

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_16to1_15_2/packets/EntityPackets.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_16to1_15_2/packets/InventoryPackets.java
Partially reverts #2007 and instead replaces it with a better solution. Rather than closing the current inventory as a new one is sent, this instead cancels any arm-swing that the client sends when swapping inventories (explained more extensively [here](https://github.com/ViaVersion/ViaVersion/pull/2007#issuecomment-678675622)).
Before:
As you can see, every time I click the stone which is supposed to open a new inventory, it just re-opens the one that opens when I left-click the glowstone. May be a bit difficult to see, but this is more easily observed from one I sent of this happening on The Hive.
After:
This has been tested extensively and no unintended side effects have been observed as a result of it.
> Rework inventory workaround to cancel animation if in an open inventory for 1.16

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/metadata/MetadataRewriter1_13To1_12_2.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/metadata/MetaIndex.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/metadata/MetadataRewriter1_9To1_8.java
This PR fixes enderman metadata translation (previously they had invalid items on 1.8 server for 1.9+ clients). Now its fixed and tested for 1.9 and 1.13
> Fixed 1.9 -> 1.8 enderman held item metadata translation

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/Protocol1_13To1_12_2.java
Hello,
I had been experiencing problems with one of my 1.8 servers kicking out players who would try to open up the Recipe Book while on newer versions, issue fixed by https://github.com/ViaVersion/ViaVersion/commit/78bb5f171f946b25afb1d9d82d9ec760e1638a8d. Although, now that they could open up the book, if they happened to have a recipe unlocked and decided to click on it, they would get kicked off the server, producing an error similar to the original bug.
I'm completely new to ViaVersion's codebase, but replicating the same approach taken by the referenced commit apparently fixes the problem all together, with no more unexpected crashes for my players.
> Fix IOB in 1.13 recipe request

- common/src/main/java/us/myles/ViaVersion/api/data/ParticleMappings.java
The ID was incorrect causing players to crash when attempting to spawn redstone dust particles. This corrects it to look for the `falling_dust` ID not the `dust` ID, like it was intended to do.
Error caused: https://gist.github.com/connorhartley/57691cd199b57edff126e10d40827308
> Fix falling dust ID in ParticleMappings

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_16to1_15_2/packets/EntityPackets.java
This fixes a bug where an entity attribute discarded for having an invalid identifier would not cause the resulting packet's length prefix to be updated, resulting in a packet that reported having more attributes that it actually did.
It also makes invalid entity attribute messages be hidden by the `suppress-conversion-warnings` config option.
> fix entity attributes length prefix

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_10to1_9_3/Protocol1_10To1_9_3_4.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_9_3to1_9_1_2/Protocol1_9_3To1_9_1_2.java
This PR fixes the changes made in sound pitch reading from 1.9.2 -> 1.9.3.
Tested with 1.9.4 client on 1.9.2 server and 1.9.4 client on 1.9.4 server using noteblocks tuned to the same pitch.
> corrected 1.9.x -> 1.10 sound pitch adjustments

- common/src/main/java/us/myles/ViaVersion/api/protocol/ProtocolVersion.java
This just adds the missing protocol versions in ranges and removes 1.6.3, 1.7 and 1.7.1 because according to [wiki.vg](https://wiki.vg/Protocol_version_numbers) these versions haven't been released and also these versions are not in the releases list in the official Minecraft launcher:
I also just removed the unecessary condition in VersionRange
> Update protocol versions

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_11to1_10/Protocol1_11To1_10.java
This possibly got broken in the rewrite in dc62394.
Fixes ender pearl throw and experience bottle throw/pickup sounds.
> Fix sound ID shift in 1.11

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_14to1_13_2/packets/WorldPackets.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_15to1_14_4/packets/WorldPackets.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_16_2to1_16_1/packets/WorldPackets.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_16to1_15_2/packets/WorldPackets.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_17to1_16_4/packets/WorldPackets.java
Replaced hardcoded values of 16 with chunk.getSections().length to make code that iterates over the chunk sections and remaps them more consistent with already present code.
> Replaced some hardcoded chunk section values

- bukkit/src/main/java/us/myles/ViaVersion/bukkit/handlers/BukkitEncodeHandler.java
Injecting a message to byte encoder beforehand would break outbound packets in ViaVersion. This solution is a good fix which won't impact anything.
> Fixed encoding not properly working with other packet reading libraries

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/packets/EntityPackets.java
This fixes 1.9 players seeing offhand swing animation when 1.8 player starts eating. 1.8 servers send an animation packet with animateionId 3 which doesn't even get handled by 1.8 clients (https://prnt.sc/100qn81). 1.9 reused this id for offhand swing animation
> [1.9 -> 1.8] Fix handling of animation 3

- buildSrc/src/main/kotlin/extensions.kt
It is a deficient part of Bunge Chat relocation. (5e227cb)
> Fix Bunge Chat relocation (ExceptionInInitializerError)

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_17to1_16_4/ClientboundPackets1_17.java
> Fixed a Title Packet Issue on 21w08a+

- api/src/main/java/us/myles/ViaVersion/api/ViaVersionConfig.java
- common/src/main/java/us/myles/ViaVersion/AbstractViaConfig.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/packets/WorldPackets.java
- common/src/main/resources/assets/viaversion/config.yml
We have noticed that blocking through viaversion is delayed.
The reason for this is that you send an interaction to ViaVersion with the sword in the main hand,
which then puts a shield in the offhand and the client then
starts an interaction packet with the offhand blocking.
A better solution would be to trigger the blocking directly via the main hand but additionally place the shield visually in the offhand.
This change also fixes the issue that sometimes the shield stays in your inventory when you block for a very short time.
> Fixes delayed shield blocking

- bukkit/src/main/java/us/myles/ViaVersion/bukkit/providers/BukkitInventoryQuickMoveProvider.java
This fixes the error when shit-clicking on the offhand slot on a 1.8 server with a 1.12 or higher client (fixes #2393)
> Fix error with shit-click on offhand slot on 1.8 servers

- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/packets/WorldPackets.java
- common/src/main/java/us/myles/ViaVersion/protocols/protocol1_9to1_8/storage/EntityTracker1_9.java
I fixed two issues of the **showShieldWhenSwordInHand** feature:
- For some reason the shield sometimes remained as a ghost item in the second hand after changing the held item slot.
The shield sync of the InventoryTracker works without any problems. [Video](https://i.imgur.com/4S9dMeG.mp4)
**Solution:** The item in the second hand will now be removed more frequently and not only when you switch off a sword.
- You could not interact with items when you quickly switch from a sword to another item. [Video](https://www.youtube.com/watch?v=IMCHrj2Do9M)
**Solution:** The item cache of the InventoryTracker will now be used to check if the player interacts with a sword because it updates way faster.
> fix showShieldWhenSwordInHand issues

- common/src/main/java/us/myles/ViaVersion/util/ReflectionUtil.java
This fixes the `java.lang.reflect.InaccessibleObjectException: Unable to make protected void java.lang.Object.finalize() throws java.lang.Throwable accessible: module java.base does not "opens java.lang" to unnamed module @4950b38` when running with Java 16 on Bukkit or Sponge 1.8. I also removed the unchecked and deprecation warnings in the ReflectionUtil class
> Fix Java 16 compatibility on Bukkit/Sponge 1.8

- bungee/src/main/java/us/myles/ViaVersion/bungee/handlers/BungeeChannelInitializer.java
- bungee/src/main/java/us/myles/ViaVersion/bungee/handlers/BungeeDecodeHandler.java
- bungee/src/main/java/us/myles/ViaVersion/bungee/handlers/BungeeEncodeHandler.java
We check if the connection is active before doing anything to fix issues in Bungee servers.
We fix:
1. Exceptions if the connection is closed.
2. Support for Bungee AntiBot systems.
Testing Info:
Base: 1.8.8 (SportPaper & FlameCord (ViaRew. & ViaVer.))
Clients: 1.7, 1.8, 1.12
Errors: None at all
> Bungee Fixes

- bungee/src/main/java/us/myles/ViaVersion/bungee/handlers/BungeeChannelInitializer.java
Bungee checks like throttle lay on the initializer. To prevent attacks or exploits we check if the channel is active before injecting.
> Don't inject if inactive

- bukkit-legacy/src/main/java/com/viaversion/viaversion/bukkit/listeners/protocol1_9to1_8/PaperPatch.java
- bukkit/src/main/java/com/viaversion/viaversion/bukkit/platform/BukkitViaLoader.java
tested with:
- Paper 1.8.8, 1.9.4, 1.11.2 (enabling)
- SportPaper 1.8.8 (enabling)
- Spigot 1.8.8 (not enabling)
> use a more fork-proof approach to enable Paper block place patch

- .gitignore
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_16to1_15_2/Protocol1_16To1_15_2.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_16to1_15_2/packets/EntityPackets.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_16to1_15_2/packets/InventoryPackets.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_16to1_15_2/storage/InventoryTracker1_16.java
Partially revert #2528 to reintroduce #2031.
The reason of this revert is that even when the player is not navigating between inventories, item drop can happen by simply pressing the drop key or throwing out of the window the item in his cursor. These two situations triggers an arm animation as for any item drop, and this was the initial issue of all these PRs.
So the solution is to completely cancel any arm animation packet going to the server when the player has an inventory opened (by reintroducing #2031). I also kept what I introduced with #2528 to prevent the arm to swing client-side during navigation.
This is tested and working, all feedbacks are welcome :)
> Cancel arm animation if in an open inventory for 1.16+

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13to1_12_2/data/MappingData.java
As partially described in #2187 the following channel names are valid but not recognized as valid:
- an empty string
- ``:``
- ``no_namespace`` (parsed as minecraft namespace)
- ``empty_path:``
- ``:empty_namespace`` (parsed as minecraft namespace)
This PR fixes all of these cases.
This PR also fixes a different issue which couldn't occur at runtime due to the first issue.
The ``protocol1_13to1_12_2.data.MappingData#validateNewChannel`` method would transform ``:path`` to ``minecraft::path`` which is invalid.
I did also remove the length check in that method because it was not necessary. The only place where this method is used does limit the length itself:
https://github.com/ViaVersion/ViaVersion/blob/e64a0fb62e8573096bee85581c2e5f263654591d/common/src/main/java/com/viaversion/viaversion/ …
> Fix channel name validation in 1.13 to 1.12.2 protocol

- bungee/src/main/java/com/viaversion/viaversion/bungee/platform/BungeeViaInjector.java
- common/src/main/java/com/viaversion/viaversion/util/SetWrapper.java
- java-compat/java-compat-unsafe/src/main/java/com/viaversion/viaversion/compatibility/unsafe/UnsafeBackedForcefulFieldModifier.java
This removes the usage of `sun.misc.Unsafe` in `BungeeViaInjector`, by injecting in the child handler, like in the Bukkit/Sponge injectors, which doesn’t require to modify a static final field, so it doesn’t require the usage of `sun.misc.Unsafe`, which may break in future Java versions.
I tested with only ViaVersion, with ViaVersion/ViaBackwards and with ViaVersion/ViaBackwards/ViaRewind, on both BungeeCord and Waterfall, with newer and older clients, and everything seems to works fine, so I guess it’s good 😃 
This should also closes #2414.
> Remove usage of `sun.misc.Unsafe` in `BungeeViaInjector`

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_9to1_8/packets/PlayerPackets.java
1.8 always opens credits screen when game state reason 4 is received.
1.9 only opens it if the value is set to 1.
This PR fixes that behaviour.
> Fixed credits screen not showing on 1.8 servers

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13_1to1_13/Protocol1_13_1To1_13.java
There has been a change in directions of the smoke effect back in 1.13.1 that has gone relatively unnoticed. Below is a comparison from before and after (including the data of each direction):
Some of the old directions are no longer reproducible as of 1.13.1, but North, South, East and West are, and this PR maps them to their new data values. For the old unsupported ones, I added a fallback to 0 (Down), or should it be something else?
> Map smoke directions from 1.13 to 1.13.1

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_9to1_8/packets/SpawnPackets.java
Fixes those client errors being spammed into the console everytime a potion is thrown
> Fixed 1.9 -> 1.8 potion metadata packet order

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_11to1_10/Protocol1_11To1_10.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_18to1_17_1/packets/WorldPackets.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_9_3to1_9_1_2/Protocol1_9_3To1_9_1_2.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_9_3to1_9_1_2/chunks/FakeTileEntity.java
Correctly fixes #2744 and potentially other block entities like furnaces which weren't fixed before
> Fixed 1.9.2 -> 1.9.3 block entity translation

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_17to1_16_4/storage/InventoryAcknowledgements.java
This fixes inventory acknowledgements not being sent again by Via if the server sends multiple with the same id within a short timespan.
> Fixed inventory acknowledgements being dropped sometimes

- bukkit/src/main/java/com/viaversion/viaversion/bukkit/providers/BukkitViaMovementTransmitter.java
Fixed packet getters in BukkitMovementTransmitter leading to sending the opposite packet (sending the ground one when flying, and the flying one when on ground) when not using the nms player ticking config option
> Fixed wrong packet in MovementTransmitter

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_19to1_18_2/Protocol1_19To1_18_2.java
Prevents sounds from being the same on 1.19 clients, simulate randomness by sending a random seed.
> Generate a random seed to simulate random sounds

- common/src/main/java/com/viaversion/viaversion/configuration/AbstractViaConfig.java
- common/src/main/java/com/viaversion/viaversion/util/Config.java
Is this good enough or should I handle this with more details ?
I also thought about handling both list the same way to make them interchangeable but maybe not a good idea.
> Safely handle bad configuration of 'block-protocols' and 'block-versions'

- bukkit/src/main/resources/plugin.yml
- bungee/src/main/java/com/viaversion/viaversion/bungee/commands/BungeeCommand.java
- velocity/src/main/java/com/viaversion/viaversion/velocity/command/VelocityCommandHandler.java
The implementation of the command suggestions themself are properly handled by the "ViaCommandHandler", but the suggestion of the command on the root node is not handled properly, so typing /via suggest /viaversion even when the user is not granted the "viaversion.admin" permission.
I also considered splitting the perm to something like "viaversion.command.use" and "viaversion.admin" to differentiate the permission of the main command from all the sub commands, but they currently all use the same permission so i think it might be good enough for now.
> Reference command permission to filter root suggestions (/via<tab>)

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_19to1_18_2/packets/EntityPackets.java
Currently, a painting mapping from 1.19.1 server -> 1.18 client works fine, but 1.19.1 -> 1.19 will map some paintings to -1, causing a client crash. This commit ensures an unknown painting ID is safely mapped to 0.
Here is a client crash caused by this issue:
```
java.lang.NullPointerException: Cannot invoke "net.minecraft.core.Holder.value()" because the return value of "net.minecraft.world.entity.decoration.Painting.getVariant()" is null
at Genesis//net.minecraft.client.renderer.entity.PaintingRenderer.render(SourceFile:33)
at Genesis//net.minecraft.client.renderer.entity.PaintingRenderer.render(SourceFile:23)
at Genesis//net.minecraft.client.renderer.entity.EntityRenderDispatcher.render(EntityRenderDispatcher.java:184)
at Genesis//net.minecraft.client.renderer.LevelRenderer.renderEntit …
```
> Use default painting mapping of 0 instead of -1

- bungee/src/main/java/com/viaversion/viaversion/BungeePlugin.java
- common/src/main/java/com/viaversion/viaversion/unsupported/UnsupportedServerSoftware.java
Since Flamecord doesn't work with ViaVersion, I think it could be great to add it as an unsupported software to log something users can understand without getting to Discord for support.
I also updated the protocol version constant check for bungeecord outdated check.
> add flamecord warning message

- bukkit/src/main/java/com/viaversion/viaversion/bukkit/handlers/BukkitEncodeHandler.java
- bukkit/src/main/java/com/viaversion/viaversion/bukkit/listeners/JoinListener.java
- bukkit/src/main/java/com/viaversion/viaversion/bukkit/listeners/LoginListener.java
- bukkit/src/main/java/com/viaversion/viaversion/bukkit/platform/BukkitViaLoader.java
- common/src/main/java/com/viaversion/viaversion/connection/ConnectionManagerImpl.java
This is a PoC implementation of a fix for #2835
The idea is that on join event (on the main thread) we set the UserConnection in the ConnectionManager, this means any other plugin requesting player info (like the user's protocol) in PlayerJoinEvent (anything above lowest priority) will get correct info. For more info on the issue refer to #2835 .
This change makes onLoginSuccess be indepotent (assumed to be called twice for each player, once on login event from main thread, and once from network thread), and adds a listener for PlayerLoginEvent on lowest priority that finds the UserConnection from the Player -> EntityPlayer -> PlayerConnection -> NetworkManager -> Channel -> Viaversion encoder -> UserConnection
Edit: 
I have tested and validated that this works as intended on sportpaper …
> Fix user connection race condition (PoC)

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_19to1_18_2/Protocol1_19To1_18_2.java
Fixes the client (1.19+) being kicked from servers if the server sends an empty json array as title text.
> Fixed 1.19 -> 1.18.2 title translation: Empty text edge case

- README.md
The README suggests to use LATEST as the version for importing the Via API as a Maven dependency. LATEST is now deprecated by Maven 3 for better reproducible builds. This pull request changes it to [4.0.0-5.0.0), which should use the latest 4.x.x release, and should work as long as they don’t decide to deprecate that. This should be updated each major version.
> Change suggested Maven version from deprecated LATEST

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_14to1_13_2/packets/WorldPackets.java
Fixes a rare error when chunk sections passed through the protocol are larger than 16 sections. Does not break anything else.
> Replaced hardcoded chunk section out of bounds check

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_9to1_8/packets/EntityPackets.java
Changed the data type of the attach state in the 1.9 -> 1.8 protocol. This does not fix anything and is just for consistency reasons. Please merge into the dev branch as well.
> Corrected 1.9 -> 1.8 ATTACH_ENTITY data reading

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13to1_12_2/packets/EntityPackets.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_14_4to1_14_3/Protocol1_14_4To1_14_3.java
As of Minecraft 1.13, a new flag has been added to the Status Effect Packet that specifically says whether a Status Effect should be displayed in-game at the top right, this PR always sets it to true if enabled in ViaConfig. So that 1.14.4+ clients on older servers have the HUD correctly.
> fixed Particle Rendering in 1.13.0 -> 1.12.2

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_16to1_15_2/packets/WorldPackets.java
Between version 1.15.2 and 1.16, the entity zombie_pigman was renamed to zombified_piglin, but mob_spawners didn't had any translation, which causes the client to spam the log with errors "Skipping Entity with id minecraft:zombie_pigman" and no entity is shown in the mob spawner.
Can be tested with a server which has version 1.8.9 until 1.15.2 and a client with version 1.16 until 1.19.2 by creating a mob spawner, and setting it with a zombified piglin spawnegg.
> Fix missing zombie_pigman (1.15.2) => zombified_piglin (1.16) translation in mob_spawner tile entity

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_19to1_18_2/Protocol1_19To1_18_2.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_19to1_18_2/packets/EntityPackets.java
Fixes the client (1.19+) being kicked from servers if the server sends an empty json array as display name for player info entries.
Basically the same fix as #3115 but for player list entries.
> Fixed 1.19 -> 1.18.2 player info display name translation: Empty text edge case

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_12to1_11_1/Protocol1_12To1_11_1.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13to1_12_2/packets/EntityPackets.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_16to1_15_2/packets/WorldPackets.java
When using a multi-server configuration, with servers which are pre-1.12, switching from 1.12 to pre-1.12 causes the recipe book to not clear.
Can be tested with a BungeeCord and two servers, one is pre-1.12 and the other one 1.12 or later. When switching from 1.12 to 1.11, the recipe book is still shown, even when unusable and containing invalid recipes.
> Fix recipe book not being empty when using a multi-server configuration, with servers which are pre-1.12.

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_19_3to1_19_1/Protocol1_19_3To1_19_1.java
1.19.3 added the CREEPER_IGNITERS tag to control what items can ignite a creeper. If not filled in, the client will assume the action did nothing and will allow items in the offhand to test on the item (I.E. a name tag on the offhand will succeed in naming the soon-to-be-blown-up creeper). 
This PR fills in that tag with the only item that was an igniter in 1.19.2, flint and steel.
> Fill in creeper igniter tag for 1.19.3

- api/src/main/java/com/viaversion/viaversion/api/configuration/ViaVersionConfig.java
- bukkit/src/main/java/com/viaversion/viaversion/bukkit/listeners/protocol1_19_4To1_19_3/ArmorToggleListener.java
- bukkit/src/main/java/com/viaversion/viaversion/bukkit/platform/BukkitViaConfig.java
- bukkit/src/main/java/com/viaversion/viaversion/bukkit/platform/BukkitViaLoader.java
- common/src/main/java/com/viaversion/viaversion/configuration/AbstractViaConfig.java
- common/src/main/resources/assets/viaversion/config.yml
1.19.4 will allow players to swap armor as long as the armor slot isn't identical to the hand slot. This PR patches that using the Bukkit API.
> Add armor toggle patch for Bukkit

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13to1_12_2/blockconnections/ConnectionData.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13to1_12_2/blockconnections/providers/BlockConnectionProvider.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13to1_12_2/blockconnections/providers/PacketBlockConnectionProvider.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13to1_12_2/blockconnections/providers/UserBlockData.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13to1_12_2/packets/WorldPackets.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13to1_12_2/storage/BlockConnectionStorage.java
Optimizes the following bottleneck:
This is a profile from the netty event thread, for a few seconds during which a ton of players (about 60) are teleported between worlds. Updating block connections for neighboring chunks was a pretty significant part of the time, causing some lag on the network thread and causing players to run behind the server for a bit.
The PR mainly caches `connection.get(BlockConnectionStorage.class)` and `blockStorage.get(index)`, both of which are taking significantly long and don't need to be ran *for every single block* when the value returned can be cached temporarily.
Note: I have not yet ran/tested these changes, but i'm still opening the PR as a draft to be able to get feedback/reviews. Will update with results once i've tested, deployed, and validated the …
> Optimize block connections on neighbour chunk calculation

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13to1_12_2/Protocol1_13To1_12_2.java
Apparently this packet is written in two different places
> Fix PlayerLookTargetProvider

- common/src/main/java/com/viaversion/viaversion/scheduler/TaskScheduler.java
Fixed https://bugs.openjdk.java.net/browse/JDK-8129861 by setting the core size of the TaskScheduler ThreadPool to 1
> Fixed high CPU usage on Java 8

- gradle/libs.versions.toml
Adventure: 4.12.0 -> 4.13.1,
FastUtil: 8.5.11 -> 8.5.12,
JUnit: 5.9.2 -> 5.9.3,
checkerQual: 3.29.0 -> 3.34.0.
Testing is suggested in case something goes wrong, other libraries have been left untouched unless ofc they can be updated too such as snakeYaml 1.
> Update 4 dependencies for CI.

- api/src/main/java/com/viaversion/viaversion/util/VersionInfo.java
ViaLoader needs this getter, because otherwise when compiling ViaLoader the plugin version string is inlined, and when someone then creates a ViaProxy / ViaFabricPlus dump, the plugin version is displayed, with which ViaLoader was compiled, and not the one that is currently loaded.
> Added VersionInfo#getVersion to bypass Java inlining

- sponge/src/main/java/com/viaversion/viaversion/sponge/platform/SpongeViaInjector.java
The [`protocolVersion`](https://jd.spongepowered.org/spongeapi/10.0.0-SNAPSHOT/org/spongepowered/api/MinecraftVersion.html#protocolVersion()) method was exposed to the API in a 1.19.4 build and 'getProtocol' no longer exists in the impl. This PR fixes the issue while maintaining compatibility with API-8.
> Fix `SpongeViaInjector#getServerProtocolVersion()` for Sponge API-10+

- .github/workflows/gradle.yml
- settings.gradle.kts
Makes the GitHub CI script morely complete by introducing rest of friendly names into the jobs as current one only has two friendly name strings included which is the setup JDK and build contexts,
For dependencies, The following is updated:
Kyori's blossom: 1.2.0 -> 1.3.1,
johnrengelman's shadow: 8.1.0 -> 8.1.1.
*(Syncable to viabackwards' repository if this PR works out properly)*
> Use friendly names in CI tasks, Update shadow and blossom.

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13to1_12_2/blockconnections/ConnectionData.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13to1_12_2/blockconnections/providers/BlockConnectionProvider.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13to1_12_2/blockconnections/providers/PacketBlockConnectionProvider.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13to1_12_2/packets/WorldPackets.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13to1_12_2/storage/BlockConnectionStorage.java
Currently when using the packet-based block storage for block connection resolving, placing a block (or breaking it) and the event being cancelled by the server, leaves fences and similar in an invalid/broken state.
Example:
The reason this is broken is that the following sequence of events occurs:
1) (prior) Load the world/chunk, all the block-states are saved per player based on the packets sent to them and computed block connections.
2) Place (or break) the block
3) Client-side, your block gets connected to the newly placed block
4) Server-side, you're sent an update that the block should be air (your place was cancelled)
5) Viaversion tries to update neighbor connections, but sees the fence as not-connected, as saved in step 1, and so skips the update.
There's not an unique solution …
> Fix missing block connection updates on cancelled place/remove

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_19to1_18_2/Protocol1_19To1_18_2.java
Through in the previous issue (#2923), the fix handle the component on title packet, but null component could also appear on action bar, teams and scoreboard objective packet and result in the same "Received unexpected null component" error, this PR handle those packets above and map it into empty component like the fix commit (https://github.com/ViaVersion/ViaVersion/commit/66b21431f22a62cc1f3d0a5cdd28bd9ea1e36944).
> Handle more null TextComponent for 1.19 to 1.18.2

- api/src/main/java/com/viaversion/viaversion/api/type/types/minecraft/PositionType.java
The Y coordinate is actually signed (Checked in 1.8 and 1.13.2)
> Fixed <= 1.14 position reading

- api/src/main/java/com/viaversion/viaversion/api/minecraft/chunks/ChunkSectionLightImpl.java
Allows rewriters/packet handlers to remove skylight from an already read chunk
> Allow skylight to be set to null

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_17to1_16_4/packets/InventoryPackets.java
The client code got changed in 1.17 -> 1.16.5 and caused maps with no map tag not being rendered in 1.17+
Had to reopen the PR because the other one got closed because I deleted my ViaVersion fork
> Fixed maps with no map id set showing up as empty on 1.17+

- common/src/main/java/com/viaversion/viaversion/rewriter/ItemRewriter.java
This fixes IndexOutOfBoundsException with 23w31a client on 1.19.4 (and older?) server
<details>
<summary>Stacktrace</summary>
```
[01:42:02 WARN]: [ViaVersion] ERROR IN Protocol1_20To1_19_4 IN REMAP OF WINDOW_ITEMS (0x12)
[01:42:02 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[01:42:02 WARN]: Packet Type: WINDOW_ITEMS, Type: Flat Item Array, Index: 3, Data: [{Unsigned Byte: 0}, {VarInt: 1}], Source 0: com.viaversion.viaversion.rewriter.ItemRewriter$2 (Anonymous), Packet ID: 18
[01:42:02 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[01:42:02 WARN]:        at …
```
> Fix itemArrayType of ItemRewriter on dev branch

- api/src/main/java/com/viaversion/viaversion/api/minecraft/chunks/DataPaletteImpl.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13to1_12_2/storage/BlockConnectionStorage.java
Improves memory allocation time when lots of players are being moved between worlds. The test setup is 80 players in 1.20, connected to a 1.8 server, being teleported at once from a world to another.
Current viaversion is using upwards of 20GB worth of memory allocations solely on DataPaletteImpl, with the applied optimizations it lowers to ~6GB~ 2.1GB (world with some empty regions) or even 800MB (world with mostly void).
Before: 
After:
The main  gains are:
- byte[] instead of int[] for the chunk data, and nothing at all for empty chunks
- Works as long as there's up to 256 different types of blocks
- If there's over 256 block types, it'll migrate over to a short[] instead
- Turns ~9.31GB of allocations into ~2.92GB, with some empty chunks 1.35GB, with mostly void 5MB
- Initializing the …
> Optimize memory allocation for data palette

- .github/workflows/gradle.yml
- .github/workflows/publish.yml
1. Updates the checkout step to version 4, *(Changelogs can be [found here](https://github.com/actions/checkout/releases/tag/v4.0.0))*
2. GitHub Actions will now automatically check for any new builds of the JDK 11 distribution instead of having to relay on the provided Ubuntu image itself.
This PR has been tested and can be safely included into dev branch.
> Update checkout to v4, Check for latest JDK 11 build.

- README.md
The Minecraft Wiki maintainers have decided to move away from Fandom. More information can be found here: <https://minecraft.wiki/w/Minecraft_Wiki:Moving_from_Fandom>.
> Update Minecraft Wiki link to new domain after fork

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_9to1_8/ItemRewriter.java
The ItemRewriter from ViaRewind uses these fields, I would like to delete the reflection code from ViaRewind by simply making the fields public so that I can use them in VR.
> Make ItemRewriter registries accessable

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_20_2to1_20/Protocol1_20_2To1_20.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_9to1_8/packets/PlayerPackets.java
Clears the packet properly instead of reading remaining bytes. Fixes issues where the code throws an exception if the packet is not originating from a ByteBuf, but was constructed via PacketWrapper.create
> Clear input buffer instead of reading remaining bytes

- common/src/main/java/com/viaversion/viaversion/commands/ViaCommandHandler.java
- common/src/main/java/com/viaversion/viaversion/commands/defaultsubs/DebugSubCmd.java
Fixed for example the bug that when you type **/viaversion debug a** it suggests all debug modes when it should only suggest **add**.
> Match current command input for sub argument tab completions

- common/src/main/resources/assets/viaversion/config.yml
1. Don't mention the Spigot page anymore as it became outdated and isn't the right place for Via* bug reports/discussions anymore.
2. Move map-1_16-world-names to the correct config block.
> config.yml cleanup and general improvements

- bukkit/src/main/java/com/viaversion/viaversion/bukkit/listeners/JoinListener.java
On 1.20.2 the `NetworkManager` field is located in the super class of `PlayerConnection`.
<details><summary>Error before this patch</summary>
```text
[ViaVersion] Couldn't find reflection methods/fields to access Channel from player.
Login race condition fixer will be disabled.
Some plugins that use ViaAPI on join event may work incorrectly.
java.lang.NoSuchFieldException: NetworkManager
at com.viaversion.viaversion.bukkit.listeners.JoinListener.findField(JoinListener.java:80) ~[?:?]
at com.viaversion.viaversion.bukkit.listeners.JoinListener.<clinit>(JoinListener.java:50) ~[?:?]
at com.viaversion.viaversion.ViaVersionPlugin.onEnable(ViaVersionPlugin.java:109) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
at …
```
> Fix reflection field search on 1.20.2

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13to1_12_2/packets/WorldPackets.java
This PR corrects the handling of invalid block ids in 1.13 -> 1.12.2. A vanilla client loads an air block instead of stone for any unknown blocks. ViaVersion should do the same as all vanilla blocks have mappings anyways, so it shouldn't be needed to return stone
> Return air instead of stone for unknown block ids

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_9to1_8/packets/EntityPackets.java
This PR fixes an issue where invalid entity equipment slot ids would cause a disconnect, while in 1.8 they don't.
> Handle invalid entity equipment slots properly

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_20_3to1_20_2/Protocol1_20_3To1_20_2.java
Fixes #3546 
Problem is: The count of the item in the chat component is parsed as string, as the json element could not detect the actual type (int). I've just added another case for the `LazilyParsedNumber` to act as int, as well as changed the default "idk what this is" case to an int. This may not be an ideal solution, but I think this whole section, may be replaced with another solution like adventure?
This just fixes the issue (on my machine)
> fix 1.20.3 chat component parsing

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_20_2to1_20/rewriter/EntityPacketRewriter1_20_2.java
This fixes an issue MCC Island (and likely other servers) are having where skin layers go missing when players switch servers. We run ViaVersion only on the proxy. Without this fix skin layers break every server switch, seems completely fixed after.
I don't know enough about Via's workings to fully understand why this fixes it but my guess is that there's some issue with the packet arriving in the wrong phase when the client doesn't go into the configuration phase first? Maybe this needs a better fix.
Found this fix because were running a very specific developer build that had 1.20.2 support but without this issue, and I reverted the one commit that made any changes and this was the only part of that commit that has any effects.
> Fix skin layers breaking for >= 1.20.2 clients on < 1.20.2 velocity proxies

- api/src/main/java/com/viaversion/viaversion/api/type/types/chunk/ChunkSectionType1_8.java
In 1.8, block ids in chunks are read as unsigned. This only fixes mods with custom blocks, translating through a modified version with custom mappings.
> Read 1.8 chunk block ids as unsigned

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_20_3to1_20_2/util/ComponentConverter.java
This fixes `/tp ~ ~ ~` crash on 1.20.3+ client connecting to 1.20.2- servers
> fix hoverEvent translation from 1.20.2 to 1.20.3

- common/src/main/java/com/viaversion/viaversion/util/Config.java
- common/src/main/java/com/viaversion/viaversion/util/InputStreamSupplier.java
The URL for the default config could be null, depending on the ClassLoader. However, getting the resource as stream is possible in more cases due to multiple datasources.
These changes allow subclasses of `com.viaversion.viaversion.util.Config` to support loading from streams as well, as `loadConfig` got an InputStream from `URL::openStream` anyway.
The method `Config::getDefaultConfigInputStream` acts as a fallback incase the default config URL is null, meaning that running systems won't affected.
Let me know if there are any questions.
> Support config loading from input stream as fallback if URL cannot be acquired

- .github/workflows/gradle.yml
- .github/workflows/publish.yml
- velocity/build.gradle.kts
1. Updates the JDK version to 17 as velocity 3.3 depends on it and because this version is much more stable,
2. Updates the setup-java dependency in CI to v4.
> Update JDK to 17, setup-java to v4

- common/src/main/java/com/viaversion/viaversion/dump/VersionInfo.java
- common/src/main/java/com/viaversion/viaversion/util/DumpUtil.java
> Only pass ProtocolVersion#toString into via dumps

- common/src/main/java/com/viaversion/viaversion/protocol/RedirectProtocolVersion.java
Some Via Addons are adding versions which are depending on already existing versions (e.g. AprilFools versions), this class can be used to generate ProtocolVersion instances which are automatically comparing against the origin version
Examples where this can be used:
https://github.com/ViaVersion/ViaAprilFools/blob/main/src/main/java/net/raphimc/viaaprilfools/api/AprilFoolsProtocolVersion.java
https://github.com/ViaVersion/ViaLegacy/blob/main/src/main/java/net/raphimc/vialegacy/api/LegacyProtocolVersion.java
https://github.com/RaphiMC/ViaBedrock/blob/main/src/main/java/net/raphimc/viabedrock/api/BedrockProtocolVersion.java
> Added RedirectProtocolVersion API to common module

- api/src/main/java/com/viaversion/viaversion/api/protocol/ProtocolManager.java
- common/src/main/java/com/viaversion/viaversion/protocol/ProtocolManagerImpl.java
- common/src/main/java/com/viaversion/viaversion/protocols/base/BaseProtocol.java
ViaLegacy and other platforms containing SPECIAL versions are adding their base protocol manually
> Don't require a base protocol for current version in BaseProtocol

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_20_5to1_20_3/rewriter/BlockItemPacketRewriter1_20_5.java
The particle id was not converted.
> Fix particle doesn't use new mapping id (1.20.5)

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_20_5to1_20_3/Protocol1_20_5To1_20_3.java
Fixes the issue where leather armor always renders as white.
In the diff between 1.20.4 and 24w07a, it seems that there are no item tags affecting the client other than `minecraft:dyeable`.
> Fix leather armor rendering (1.20.5)

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_11to1_10/packets/InventoryPackets.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_12to1_11_1/packets/InventoryPackets.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13to1_12_2/packets/InventoryPackets.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_9to1_8/packets/PlayerPackets.java
Legacy (<=1.12.2) versions of minecraft are using .equals() to compare the custom payload channels
> Fixed legacy custom payload channel comparisons

- api/src/main/java/com/viaversion/viaversion/api/rewriter/ItemRewriter.java
Since these methods are completely optional and platforms like ViaRewind don't need them, making them nullable/optional seems like better API design for me.
> Make ItemRewriter type getters nullable and optional

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_9to1_8/packets/EntityPackets.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_9to1_8/packets/SpawnPackets.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_9to1_8/storage/EntityTracker1_9.java
Minecraft doesn't buffer metadata when the entity doesn't exist, so there is no reason for us to do this, this has probably caused tons of issues in the past were ViaVersion was tracking invalid metadata which Vanilla's clients just throw away.
> Remove entity metadata buffering in 1.8->1.9

- common/src/main/java/com/viaversion/viaversion/ViaManagerImpl.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_11to1_10/Protocol1_11To1_10.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_11to1_10/metadata/MetadataRewriter1_11To1_10.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_11to1_10/packets/InventoryPackets.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_11to1_10/rewriter/BlockEntityRewriter.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_11to1_10/rewriter/EntityIdRewriter.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13to1_12_2/task/TabCompleteThread.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_18to1_17_1/data/BlockEntityIds.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_18to1_17_1/packets/WorldPackets.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_9_3to1_9_1_2/Protocol1_9_3To1_9_1_2.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_9_3to1_9_1_2/data/FakeTileEntity.java
Just some very minor stuff I noticed while going through older protocols, 1.8 will get it's own pull request once I am done with ViaRewind
> Fix minor inconsistencies in protocol packages

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13to1_12_2/data/ComponentRewriter1_13.java
Move away from ViaNBT's SNBT parsing and replaces the code with proper MCStructs parsing
> Rewrite 1.12.2->1.13 ComponentRewriter

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_12to1_11_1/rewriter/ChatItemRewriter.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13to1_12_2/data/ComponentRewriter1_13.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_19_1to1_19/Protocol1_19_1To1_19.java
- common/src/main/java/com/viaversion/viaversion/util/ComponentUtil.java
- common/src/main/java/com/viaversion/viaversion/util/SerializerVersion.java
- common/src/main/java/com/viaversion/viaversion/util/TagUtil.java
Allows us to re-use the component conversion abstraction in other projects as well.
> Add conversion methods to SerializerVersion and replace missing MCStructs usages

- api/src/main/java/com/viaversion/viaversion/api/rewriter/ItemRewriter.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13to1_12_2/packets/InventoryPackets.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_14to1_13_2/packets/InventoryPackets.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_20_5to1_20_3/rewriter/BlockItemPacketRewriter1_20_5.java
Adding ItemRewriter#nbtTagName utils to prefix nbt tags with a consistent format: 
`<Platform>|<Protocol name>|<original nbt name>`
> Make ViaVersion fake nbt format consistent

- api/src/main/java/com/viaversion/viaversion/api/protocol/remapper/PacketHandlers.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_12to1_11_1/packets/InventoryPackets.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13_1to1_13/packets/InventoryPackets.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13_2to1_13_1/packets/InventoryPackets.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13to1_12_2/packets/InventoryPackets.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_14to1_13_2/packets/InventoryPackets.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_16to1_15_2/Protocol1_16To1_15_2.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_20_2to1_20/Protocol1_20_2To1_20.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_9to1_8/packets/PlayerPackets.java
This PR fixes pre 1.20 custom payload handling, Minecraft try catched the whole data/content reading code causes errors to *silently* fail, here the pre 1.20 custom payload handler:
Therefore I introduced PacketHandlers#handleSoftFail to line up with older protocols code
> Handle errors properly in <= 1.20 custom payload reading

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_9to1_8/metadata/MetaIndex.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_9to1_8/storage/EntityTracker1_9.java
There is no reason why Via should track or remap metadata that doesn't exist in both 1.8 and 1.9. I believe this was a hotfix back in the day when metadata errors weren't caught like today but just passed to the user.
> Remove non existing metadata from MetaIndex

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_9to1_8/storage/EntityTracker1_9.java
1.8 can handle out of range values for the horse armor and will just not show any armor, 1.9+ clients will get exceptions and won't render the entity at all, this is nothing EchoPet related so I improved the fix to filter bad values in general.
1.8 handling:
> Improve horse armor patch in 1.8->1.9

- api/src/main/java/com/viaversion/viaversion/api/minecraft/metadata/types/MetaType1_8.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_9to1_8/metadata/MetaIndex.java
We don't need this and can just check if **getOldType()** is null
> Remove MetaType1_8#NonExistent

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13to1_12_2/metadata/MetadataRewriter1_13To1_12_2.java
Fixes 1.13 -> 1.12.2 block state metadata translation by applying the transforms in the correct order (Previously it would first try to get the 1.13 block state with the raw 1.12.2 value instead of converting the 1.12.2 value to a proper 1.12.2 blockstate first)
> Fix 1.13 -> 1.12.2 block state metadata translation

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13_1to1_13/metadata/MetadataRewriter1_13_1To1_13.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13to1_12_2/metadata/MetadataRewriter1_13To1_12_2.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_14to1_13_2/metadata/MetadataRewriter1_14To1_13_2.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_15to1_14_4/metadata/MetadataRewriter1_15To1_14_4.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_16_2to1_16_1/metadata/MetadataRewriter1_16_2To1_16_1.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_16to1_15_2/metadata/MetadataRewriter1_16To1_15_2.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_17to1_16_4/packets/EntityPackets.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_18to1_17_1/packets/EntityPackets.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_19_3to1_19_1/packets/EntityPackets.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_19to1_18_2/packets/EntityPackets.java
- common/src/main/java/com/viaversion/viaversion/rewriter/EntityRewriter.java
This PR fixes block state reading in versions below 1.19.4 where there was only a block state type which is optional, we can probably also rename some of the meta type fields with ViaVersion 5.
1.19.3 code:
1.19.4 code:
> Handle block states optional in <1.19.4

- common/src/main/java/com/viaversion/viaversion/util/Config.java
Fixes error when the config file is in the current working directory and not within a subfolder
> Fix config read/write error when parent file is null

- api/src/main/java/com/viaversion/viaversion/util/IdAndData.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13to1_12_2/Protocol1_13To1_12_2.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13to1_12_2/packets/InventoryPackets.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13to1_12_2/packets/WorldPackets.java
Basically ViaBackwards's Block class but with some additions and error handlers for ViaLegacy/ViaRewind. This replaces https://github.com/ViaVersion/ViaLegacy/blob/main/src/main/java/net/raphimc/vialegacy/api/model/IdAndData.java and https://github.com/ViaVersion/ViaBackwards/blob/dev/common/src/main/java/com/viaversion/viabackwards/utils/Block.java and also some otherwise dirty conversions in existing protocols.
> Add IdAndData util and replace conversions

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13to1_12_2/packets/InventoryPackets.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_16to1_15_2/Protocol1_16To1_15_2.java
Since VV supports both server and client side, it makes more sense to use client/server bound as wording since incoming/outgoing will always be wrong on one side. Also changed 1.12->1.13 handlers to print the correct channel name.
> Replace incoming/outgoing usages with client/server bound

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_9to1_8/ItemRewriter.java
At some point in the future I want to remove fixJson() completely as it doesn't handle most cases and doesn't work most of the time.
Closes https://github.com/ViaVersion/ViaVersion/issues/3413
Before (Hypixel using a 1.20.4 client with ViaFabricPlus):
After (same setup):
> Push book contents through component conversion in 1.8->1.9

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_12to1_11_1/Protocol1_12To1_11_1.java
The current code doesn't make any sense as it converts an existing **JsonElement** to a string and then back to a **JsonElement**, there is no reason to do this and since I want to remove fixJson() I would like to change this.
> Remove Protocol1_9To1_8#FIX_JSON usage in 1.11->1.12

- common/src/main/java/com/viaversion/viaversion/util/ComponentUtil.java
- common/src/main/java/com/viaversion/viaversion/util/SerializerVersion.java
MCStructs has multiple methods for parsing jsons depending on the version, we should use them correctly in our wrapper to support all possible cases of components.
> Use correct deserialization method in SerializerVersion#toComponent

- api/src/main/java/com/viaversion/viaversion/api/configuration/ViaVersionConfig.java
- common/src/main/java/com/viaversion/viaversion/configuration/AbstractViaConfig.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_14to1_13_2/metadata/MetadataRewriter1_14To1_13_2.java
- common/src/main/resources/assets/viaversion/config.yml
A better solution for this would be to despawn the ocelot and spawn a cat in its place, but that would require a lot of data tracking and is not worth the effort.
_Closes_: https://github.com/ViaVersion/ViaVersion/issues/2975
> Add setting for ocelot->cat translation in 1.13.2->1.14

- api/src/main/java/com/viaversion/viaversion/api/configuration/ViaVersionConfig.java
- common/src/main/java/com/viaversion/viaversion/configuration/AbstractViaConfig.java
- common/src/main/resources/assets/viaversion/config.yml
Older servers might not expect the behaviour to change, also added a better description of what the setting actually does.
> Change default value for new ocelot setting

- api/src/main/java/com/viaversion/viaversion/api/configuration/ViaVersionConfig.java
- bukkit-legacy/src/main/java/com/viaversion/viaversion/bukkit/listeners/protocol1_9to1_8/DeathListener.java
- common/src/main/java/com/viaversion/viaversion/configuration/AbstractViaConfig.java
- common/src/main/java/com/viaversion/viaversion/legacy/bossbar/CommonBoss.java
- common/src/main/java/com/viaversion/viaversion/protocols/base/BaseProtocol1_7.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_16to1_15_2/packets/InventoryPackets.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_9to1_8/ItemRewriter.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_9to1_8/Protocol1_9To1_8.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_9to1_8/metadata/MetaIndex.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_9to1_8/metadata/MetadataRewriter1_9To1_8.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_9to1_8/packets/EntityPackets.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_9to1_8/packets/InventoryPackets.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_9to1_8/packets/PlayerPackets.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_9to1_8/packets/WorldPackets.java
- common/src/main/java/com/viaversion/viaversion/util/ComponentUtil.java
- common/src/main/resources/assets/viaversion/config.yml
Initial commit of using MCStructs in older protocols in order to fix tons of bugs existing with the current code base. For example, it's currently not possible to write "null" on a sign since the old conversion code would just throw away data.
> Replace string->component conversion in 1.8->1.9

- common/src/main/java/com/viaversion/viaversion/util/TagUtil.java
Required in ViaBackwards where rewriting of chat types requires the handling to be optional since chat_types are optional and can be skipped by the server
> Add optional registry utils to TagUtil

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_20_5to1_20_3/data/DamageTypes1_20_3.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_20_5to1_20_3/rewriter/EntityPacketRewriter1_20_5.java
Minecraft 1.20.4 and earlier silently overrides the previous values if multiple registry elements have the same id (Tested using a Fabric 1.20.4 mod by parsing a registry sent by a server and then printing the parsed objects).
> Handle duplicated registry ids in 1.20.3->.5

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_20_5to1_20_3/rewriter/EntityPacketRewriter1_20_5.java
Fixes entity effects not showing because the alpha channel was missing (which got added in 1.20.5 and was previously always 1, so we are using 1.20.4's default value here). Area effect clouds are still broken, but that's more likely an issue with the handler itself.
> Add alpha to particle colors in 1.20.3->.5

- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_13to1_12_2/Protocol1_13To1_12_2.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_16to1_15_2/Protocol1_16To1_15_2.java
- common/src/main/java/com/viaversion/viaversion/protocols/protocol1_9to1_8/Protocol1_9To1_8.java
Match newer protocols and prevent hard written packet ids.
> [ci skip] Use login/status packet enums in older protocols

- bukkit/src/main/java/com/viaversion/viaversion/ViaVersionPlugin.java
- bukkit/src/main/java/com/viaversion/viaversion/bukkit/platform/BukkitViaConfig.java
- bungee/src/main/java/com/viaversion/viaversion/BungeePlugin.java
- bungee/src/main/java/com/viaversion/viaversion/bungee/platform/BungeeViaConfig.java
- common/src/main/java/com/viaversion/viaversion/configuration/AbstractViaConfig.java
- common/src/main/java/com/viaversion/viaversion/util/Config.java
- common/src/test/java/com/viaversion/viaversion/common/dummy/TestConfig.java
- common/src/test/java/com/viaversion/viaversion/common/dummy/TestPlatform.java
- sponge/src/main/java/com/viaversion/viaversion/SpongePlugin.java
- sponge/src/main/java/com/viaversion/viaversion/sponge/platform/SpongeViaConfig.java
- velocity/src/main/java/com/viaversion/viaversion/VelocityPlugin.java
- velocity/src/main/java/com/viaversion/viaversion/velocity/platform/VelocityViaConfig.java
There is no reason to keep a separate logger for config files, this also doesn't work as intended since creating new Java loggers isn't really possible (they don't match the usually formatting Via.getPlatform().getLogger() would provide). This PR deletes the logger and uses the global/main logger provided by the platform, this has been tested with bukkit.
Before:
After:
> Use global logger for configs, delete Config#LOGGER

- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_3to1_20_5/rewriter/BlockItemPacketRewriter1_20_5.java
Makes the explosion tag optional like it is in 1.20.4 so the tooltip shows the correct duration when crafting a firework, also fixes the type used for Flight which is byte in 1.20.4
Before:
After:
1.20.4 parsing code:
> Fix firework rewriting in 1.20.3->.5

- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_3to1_20_5/rewriter/BlockItemPacketRewriter1_20_5.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_3to1_20_5/rewriter/StructuredDataConverter.java
Makes LodestonePos and LodestoneDimension optional like in 1.20.4, I'm not sure if the handling is 100% correct (e.g. when having only LodestoneDimension 1.20.4 would still show a glint while 1.20.6 now wouldn't) but issues https://github.com/ViaVersion/ViaBackwards/issues/755 and https://github.com/ViaVersion/ViaVersion/issues/3861 should be fixed now.
> Fixup LODESTONE_TRACKER rewriting in 1.20.3->.5 and backwards

- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_3to1_20_5/rewriter/BlockItemPacketRewriter1_20_5.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_3to1_20_5/rewriter/StructuredDataConverter.java
Fixes flight duration having the wrong type and also adds duration 1 as default value, it looks like 1.20.6 stopped sending default values to the client like 1.20.4 (so we will need to add them manually for every item where it matters).
> Fix FIREWORKS rewriting in 1.20.5->.3

- common/src/main/java/com/viaversion/viaversion/util/ComponentUtil.java
Looking at the git history and the old code it seems that this was missed previously, item name in 1.12->1.13 and item lore in 1.13->1.14 should both be italic default (I tested this using native server and client versions).
> Fixup ComponentUtil#legacyToJsonString behavior with styles

- bukkit/src/main/resources/plugin.yml
PS support got moved to https://github.com/ViaVersionAddons/ProtocolSupportCompat, so I believe this can be removed. Not sure if we could remove other dependencies as well like **PacketListenerApi**
> Remove outdated dependencies/plugins from plugin.yml

- api/src/main/java/com/viaversion/viaversion/api/minecraft/item/DataItem.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_12_2to1_13/Protocol1_12_2To1_13.java
Changes the DataItem copy method to also copy the NBT tag (Just like StructuredItem also copies the structured data). Also removed copy constructor as StructuredItem also doesn't have one
> Perform deep copy in DataItem#copy

- common/src/main/java/com/viaversion/viaversion/protocols/v1_8to1_9/storage/EntityTracker1_9.java
Servers can send sound packets where the positions have a slight offset. This PR aims to improve the detection to account for that.
Closes https://github.com/ViaVersion/ViaFabricPlus/issues/333
> Improve block break/place detection in 1.8->1.9

- api/src/main/java/com/viaversion/viaversion/api/minecraft/item/DataItem.java
Most protocols don't have the data field, and in theory we should have a separate Item class for 1.13-1.20.4 but having a second constructor is probably fine.
> Add DataItem constructor without data short

- common/src/main/java/com/viaversion/viaversion/util/ComponentUtil.java
We have to count the actual byte length in the correct encoding here, also using the correct limitation writeUTF() has which is **65535 (Short.MAX_VALUE * 2 + 1)**.
Closes https://github.com/ViaVersion/ViaFabric/issues/324
(I haven't checked if the original issue is still fixed by this, but I'm quite sure it is)
> Fixup ComponentUtil#trimStrings detection

- api/src/main/java/com/viaversion/viaversion/api/configuration/ViaVersionConfig.java
- common/src/main/java/com/viaversion/viaversion/configuration/AbstractViaConfig.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_3to1_20_5/data/MaxStackSize1_20_3.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_3to1_20_5/rewriter/BlockItemPacketRewriter1_20_5.java
- common/src/main/resources/assets/viaversion/config.yml
1.20.4 can send items which have a bigger amount than vanilla usually accepts, and the client doesn't validate it, 1.20.5 on the other hand checks against MAX_STACK_SIZE, meaning we should set MAX_STACK_SIZE to always have the item amount to emulate old behavior. Inventory actions are broken in both versions after sending an iron sword with a stack size of 64, so /shrug about that.
Fixes https://github.com/ViaVersion/ViaVersion/issues/3882
> Handle items with invalid amount in 1.20.3->.5

- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_3to1_20_5/rewriter/StructuredDataConverter.java
Should be added into the BlockEntityTag, see forward conversion. Closes https://github.com/ViaVersion/ViaBackwards/issues/763
> Wrap block entity tags inside root tag in 1.20.5->.3

- bukkit/src/main/java/com/viaversion/viaversion/bukkit/platform/BukkitViaConfig.java
- common/src/main/resources/assets/viaversion/config.yml
- velocity/src/main/java/com/viaversion/viaversion/velocity/platform/VelocityViaConfig.java
Another pull request will add them into ViaBungee to prevent bloating the config.yml with platform settings which aren't considered as mainly supported anymore.
> Remove bungee options from config.yml

- api/build.gradle.kts
- build-logic/src/main/kotlin/extensions.kt
- build-logic/src/main/kotlin/via.base-conventions.gradle.kts
- build-logic/src/main/kotlin/via.shadow-conventions.gradle.kts
- build-logic/src/main/kotlin/via.standard-conventions.gradle.kts
- build.gradle.kts
- bukkit/build.gradle.kts
- common/build.gradle.kts
- universal/build.gradle.kts
- velocity/build.gradle.kts
There isn't really much a point to publishing either template or compat submodules to the repository server as they shouldn't be depended on anyway, I think we should also consider not publishing some of the platform impls as well, fabric/velocity, for example, can't and shouldn't be used at all. (Not sure about bukkit). I decided to come up with this because we now have platforms which are external (sponge/bungee) and changed artifacts, making it not really possible to publish them at all (At least not in the classic way with com.viaversion.viaversion-<name>).
Not sure if extensions#publishJavaComponents should be kept or not, can be removed if you want.
If we agree on something here, I'll open a PR to ViaBackwards as well and do the same for ViaRewind.
> Restructure build-system to only publish important/usable modules

- common/src/main/java/com/viaversion/viaversion/protocols/v1_13_2to1_14/rewriter/EntityPacketRewriter1_14.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_13to1_13_1/rewriter/EntityPacketRewriter1_13_1.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_14_4to1_15/rewriter/EntityPacketRewriter1_15.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_15_2to1_16/rewriter/EntityPacketRewriter1_16.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_16_1to1_16_2/rewriter/EntityPacketRewriter1_16_2.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_16_4to1_17/rewriter/EntityPacketRewriter1_17.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_18_2to1_19/rewriter/EntityPacketRewriter1_19.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_19_1to1_19_3/rewriter/EntityPacketRewriter1_19_3.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_19_3to1_19_4/rewriter/EntityPacketRewriter1_19_4.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_19_4to1_20/rewriter/EntityPacketRewriter1_20.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_2to1_20_3/rewriter/EntityPacketRewriter1_20_3.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_3to1_20_5/rewriter/EntityPacketRewriter1_20_5.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_20to1_20_2/rewriter/EntityPacketRewriter1_20_2.java
- common/src/main/java/com/viaversion/viaversion/rewriter/EntityRewriter.java
- template/src/main/java/com/viaversion/viaversion/template/protocols/rewriter/EntityPacketRewriter1_99.java
Deduplicates some common code by moving out minecart block state rewriting into an own handler like other common metadata rewriters
> Add EntityRewriter#registerBlockStateHandler

- api/src/main/java/com/viaversion/viaversion/api/type/types/item/ItemType1_20_5.java
Minecraft's 1.20.5 item write code checks if the item is empty (item-type == null or air, count <= 0), so we also have to do this to not send broken items to the client. 
Closes https://github.com/ViaVersion/ViaVersion/issues/3881
1.20.5 logic:
> Add missing conditions to 1.20.5 item type writing

- common/src/main/java/com/viaversion/viaversion/protocols/v1_10to1_11/data/EntityMappings1_11.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_10to1_11/rewriter/ItemPacketRewriter1_11.java
Moves out handling to the actual item rewriter to prevent the code being executed in ViaBackwards, also adding the missing toServer logic.
> Handle negative items correctly in 1.10->1.11

- common/src/main/java/com/viaversion/viaversion/protocols/v1_11to1_11_1/rewriter/ItemPacketRewriter1_11_1.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_12_2to1_13/rewriter/ItemPacketRewriter1_13.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_8to1_9/rewriter/ItemPacketRewriter1_9.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_9_3to1_10/rewriter/ItemPacketRewriter1_10.java
Makes the API more consistent since those types are exposed via the api module and the ItemRewriter interface.
> Add missing item types to item rewriter implementations

- api/src/main/java/com/viaversion/viaversion/api/command/ViaVersionCommand.java
- common/src/main/java/com/viaversion/viaversion/commands/ViaCommandHandler.java
Adds API so ViaLoader and ViaFabricPlus can properly unload sub commands which are not supported or working.
> Add method to remove sub commands from command handler

- api/src/main/java/com/viaversion/viaversion/api/minecraft/GameMode.java
Vanilla fallbacks to SURVIVAL and doesn't throw any errors, also NOT_SET was missing previously.
> Fix GameMode#getById behaviour in 1.8->1.9

- common/src/main/java/com/viaversion/viaversion/rewriter/ItemRewriter.java
Allows VB (and other protocols in the future) to rewrite both window title and type at the same time.
> Add handleMenuType function to ItemRewriter

- api/src/main/java/com/viaversion/viaversion/api/minecraft/item/StructuredItem.java
Returns a generic Item[] instead of a StructuredItem[] in order to avoid issues when the array content is converted to DataItem's
> Return generic Item array in StructuredItem#emptyArray

- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_3to1_20_5/rewriter/BlockItemPacketRewriter1_20_5.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_8to1_9/rewriter/ItemPacketRewriter1_9.java
Can be tested by giving a written_book using give which will show "Invalid book tag" when openend, after getting in creative mode those line will disappear because VV puts a dummy pages tage inside the book, this PR fixes it.
> Backup original book pages for creative mode clients in 1.8->1.9

- README.md
We sometimes had people asking in the discord for this, and since ViaLoader covers most use cases for an own platform implementation, it would make sense to advertise it below the API section.
> [ci skip] Advertise ViaLoader in README file

- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_2to1_20_3/rewriter/BlockItemPacketRewriter1_20_3.java
Solves the TODO; Looking at the game code they seem to just iterate over the compound tag and get all entries as string tag just like the normal pages tag:
> Rewrite filtered_pages in 1.20.2->1.20.3

- bukkit/src/main/java/com/viaversion/viaversion/bukkit/platform/BukkitViaConfig.java
- common/src/main/java/com/viaversion/viaversion/configuration/AbstractViaConfig.java
- velocity/src/main/java/com/viaversion/viaversion/velocity/platform/VelocityViaConfig.java
Adds globalized lists for unsupported options, so we don't have to update every platform once we add/change settings.
> Rework unsupported config options in AbstractViaConfig

- api/src/main/java/com/viaversion/viaversion/api/type/types/ComponentType.java
Matches the ComponentRewriter, we mostly can't do anything with the json anyway.
> Only print broken json in component type when debug mode is enabled

- common/src/main/java/com/viaversion/viaversion/ViaManagerImpl.java
RK and I have opened several pull requests in the last months and took care of legacy versions, while we should still mark them as legacy issues on GH, I don't want to scare people from reporting them since I still maintain legacy protocols and fix issues.
My pull requests:
https://github.com/ViaVersion/ViaVersion/pull/3981 
https://github.com/ViaVersion/ViaVersion/pull/3952 
https://github.com/ViaVersion/ViaVersion/pull/3947 
https://github.com/ViaVersion/ViaVersion/pull/3939
https://github.com/ViaVersion/ViaVersion/pull/3921 
https://github.com/ViaVersion/ViaVersion/pull/3920 
https://github.com/ViaVersion/ViaVersion/pull/3886 
https://github.com/ViaVersion/ViaVersion/pull/3868 
https://github.com/ViaVersion/ViaVersion/pull/3834 
https://github.com/ViaVersion/ViaVersion/pull/3821 …
> Update legacy Minecraft version warning

- common/src/main/java/com/viaversion/viaversion/protocols/v1_8to1_9/rewriter/EntityPacketRewriter1_9.java
The previous attack speed value would still show a slight cooldown, the new value removes the cooldown entirely.
The bug that was mentioned in the comment above the code doesn't seem to happen in modern version (1.21) from testing.
I wasn't able to reproduce the bug in 1.9 also.
The reason the value is 23 is because I tested ingame using a sword until the cooldown dissapeared.
> Change Attack Speed for 1.8 -> 1.9

- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_5to1_21/rewriter/BlockItemPacketRewriter1_21.java
MC 1.21 changed the rarity of a trident to EPIC and of a piglin banner pattern to UNCOMMON which causes the item name to have a different color than in 1.20.6.
> Handle rarity changes in trident/banner pattern item in 1.20.5->1.21

- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_3to1_20_5/rewriter/BlockItemPacketRewriter1_20_5.java
This PR adds several fixes for older protocols using the new item data components.
This first fix adds instant sword blocking on 1.8 servers (It doesn't rely on inventory tracking and thus always works and has zero delay). The consume time has been set to the same value a 1.8 client uses (3600 seconds). The fix has been tested on a 1.8 server and works with or without the old shield blocking fix.
The second fix changes the crossbow max damage on <= 1.17.1 servers to fix desynced visuals on newer clients.
> Add several fixes using item data components

- common/src/main/java/com/viaversion/viaversion/rewriter/ItemRewriter.java
Required for ViaBackwards where we need to rewrite the translation key (and it also doesn't hurt to have this in forward protocols).
Closes https://github.com/ViaVersion/ViaBackwards/issues/819
> Call component rewriter in pre 1.20.3 advancement handler

- common/src/main/java/com/viaversion/viaversion/protocols/v1_15_2to1_16/rewriter/EntityPacketRewriter1_16.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_18_2to1_19/rewriter/EntityPacketRewriter1_19.java
1.14.4 and below never kept player attributes when respawning and 1.15.x always kept them
> Fix respawn "keep data" translation

- api/src/main/java/com/viaversion/viaversion/api/type/types/item/StructuredDataType.java
Ensures the proper exception is thrown when the server sends an out-of-bounds value, MC performs the same logic.
> Validate index when reading structured data type

- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_3to1_20_5/rewriter/BlockItemPacketRewriter1_20_5.java
Uses the correct SNBT parser (1.14) instead of 1.12
> Use SerializerVersion#toTag when converting 1.20.3->.5 block predicates

- api/src/main/java/com/viaversion/viaversion/api/protocol/version/VersionProvider.java
- common/src/main/java/com/viaversion/viaversion/protocols/base/BaseProtocol.java
Adds VersionProvider#getClientProtocol which can be optionally implemented, this is needed for platforms like ViaProxy/ViaFabric which allow versions other than RELEASE (april fools) to join. Reason for this is that ProtocolVersion#getProtocol only supports RELEASE.
> Allow base protocols to set client version

- common/src/main/java/com/viaversion/viaversion/protocols/base/BaseProtocol.java
- velocity/src/main/java/com/viaversion/viaversion/VelocityPlugin.java
- velocity/src/main/java/com/viaversion/viaversion/velocity/platform/VelocityViaLoader.java
1. Allows the version provider to get the client version sent through the handshake packet
2. Change ViaVersions loading order in Velocity to LATE so plugins can inject after VV using LAST
> Apply required changes for ViaAprilFools

- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_5to1_21/rewriter/ComponentRewriter1_21.java
- common/src/main/java/com/viaversion/viaversion/util/TagUtil.java
Since items inside the container component can also contain attribute modifiers, we need to handle them as well since the client would get kicked otherwise for the missing id nbt. While this works for now, we should rewrite our 1.21+ component rewriters to fully parse the item as soon as the ComponentRewriter1_20_5 is finished.
Closes https://github.com/ViaVersion/ViaVersion/issues/3968
> Handle attribute_modifiers inside container components in 1.20.5->1.21

- common/src/main/java/com/viaversion/viaversion/dump/VersionInfo.java
- common/src/main/java/com/viaversion/viaversion/util/DumpUtil.java
VV can only load on RELEASE servers and since it was listed above server protocol/version it could be confused with the ViaVersion version type.
> Remove version type from dump

- api/src/main/java/com/viaversion/viaversion/api/ViaManager.java
- common/src/main/java/com/viaversion/viaversion/ViaManagerImpl.java
- velocity/src/main/java/com/viaversion/viaversion/velocity/platform/VelocityViaLoader.java
Adds API so platforms can execute code after the platform implementation has executed their loading code (for example to override providers).
> Add ViaManager#addPostEnableListener

- api/src/main/java/com/viaversion/viaversion/api/protocol/version/VersionProvider.java
Most platforms won't ever throw an error and usually ViaVersion shouldn't even load when the server version can't be found. Therefore, I added this bouncer function, so I don't need to try catch my code in ViaLoader/VFP where an exception is never thrown
> Add VersionProvider#getServerProtocol

- .github/dependabot.yml
- .github/workflows/update-gradle-wrapper.yml
Prevents manual/unregular commits of updating both GH actions and the Gradle wrapper, sadly dependabot doesn't support Gradle Version Catalogs so it can't be used for dependencies.
> Setup dependabot for GH Actions and add workflow for updating Gradle

- common/src/main/java/com/viaversion/viaversion/protocol/RedirectProtocolVersion.java
- common/src/main/java/com/viaversion/viaversion/protocols/base/InitialBaseProtocol.java
This way, we should be able to get rid of manually adding the base protocol in projects like ViaAprilFools: https://github.com/ViaVersion/ViaAprilFools/blob/main/common/src/main/java/net/raphimc/viaaprilfools/protocol/s3d_sharewaretov1_14/Protocol3D_SharewareTo1_14.java#L87
> Use RedirectProtocolVersion#getOrigin in InitialBaseProtocol if possible

- common/src/main/java/com/viaversion/viaversion/protocols/base/InitialBaseProtocol.java
This is currently not possible without manually added base protocols which is the case in both ViaLegacy/ViaBedrock. This way we can get rid of it completely: https://github.com/ViaVersion/ViaLegacy/blob/main/src/main/java/net/raphimc/vialegacy/api/protocol/PreNettyBaseProtocol.java
> Allow protocols to handle client intention packet

- common/src/main/java/com/viaversion/viaversion/protocol/RedirectProtocolVersion.java
- common/src/main/java/com/viaversion/viaversion/protocols/base/InitialBaseProtocol.java
ViaBedrock has its own base protocol and needs to be excluded from the detection.
> Add more API for base protocols and skip manually added ones.

- api/src/main/java/com/viaversion/viaversion/api/protocol/ProtocolManager.java
- common/src/main/java/com/viaversion/viaversion/protocol/ProtocolManagerImpl.java
- common/src/main/java/com/viaversion/viaversion/protocols/base/InitialBaseProtocol.java
Splits the base protocol list in clientbound and serverbound. Useful when client and server version are not both 1.7+ (ViaLegacy, ViaBedrock)
Related to https://github.com/ViaVersion/ViaVersion/pull/4106
> Split base protocols list

- api/src/main/java/com/viaversion/viaversion/api/configuration/ViaVersionConfig.java
- common/src/main/java/com/viaversion/viaversion/configuration/AbstractViaConfig.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_2to1_20_3/Protocol1_20_2To1_20_3.java
- common/src/main/resources/assets/viaversion/config.yml
Useful for minigame servers where scoreboard numbers are always used purely for ordering purposes. Enabling the config makes it so 1.20.3+ clients will see the scoreboard without the red numbers on the right.
Tested on a 1.8 server with 1.21.1 client, both with the setting off and on, produces the expected results
> Add option to hide scoreboard numbers

- api/src/main/java/com/viaversion/viaversion/api/minecraft/Particle.java
ViaBedrock uses Particle objects in the particle mappings and I need to copy the particle before sending it, else VV messes up the data in the mappings due to object mutation
> Add Particle#copy

- api/src/main/java/com/viaversion/viaversion/api/protocol/packet/PacketWrapper.java
- common/src/main/java/com/viaversion/viaversion/protocol/packet/PacketWrapperImpl.java
- common/src/main/java/com/viaversion/viaversion/protocols/base/v1_7/ServerboundBaseProtocol1_7.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_8to1_9/Protocol1_8To1_9.java
Removes the special handling in Protocol1_8To1_9 and always send the correct/expected data by the client in ServerboundBaseProtocol1_7 itself. Also prevent sending the packet through the protocol pipeline since packet/format changes should also be handled inside the base protocol.
> Add PacketWrapper#sendFutureRaw, cleanup login disconnect handling.

- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_3to1_20_5/Protocol1_20_3To1_20_5.java
- common/src/main/java/com/viaversion/viaversion/rewriter/ComponentRewriter.java
Closes https://github.com/ViaVersion/ViaFabricPlus/issues/529. Decided to keep this only in this very protocol since joining this server worked with older ViaFabricPlus versions for MC 1.20.4.
> Rewrite display name component in player info packet in 1.20.3->.5

- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_3to1_20_5/rewriter/BlockItemPacketRewriter1_20_5.java
Adds back the old "Invalid book tag" view which mc 1.20.4 and older had when the book compound tag was invalid, the logic is 1:1 with how the vanilla client detects it.
> Fix invalid book view not visible in 1.20.3->.5

- api/src/main/java/com/viaversion/viaversion/api/data/entity/EntityTracker.java
- common/src/main/java/com/viaversion/viaversion/data/entity/EntityTrackerBase.java
-1 can be used as valid entity id and should not be used as placeholder for not set.
> Add EntityTrackerBase#hasClientEntityId and don't use -1 as not set indicator

- api/src/main/java/com/viaversion/viaversion/api/connection/UserConnection.java
- api/src/main/java/com/viaversion/viaversion/api/data/entity/EntityTracker.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/ClientWorld.java
- common/src/main/java/com/viaversion/viaversion/connection/UserConnectionImpl.java
- common/src/main/java/com/viaversion/viaversion/data/entity/EntityTrackerBase.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_10to1_11/Protocol1_10To1_11.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_10to1_11/rewriter/EntityPacketRewriter1_11.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_11_1to1_12/Protocol1_11_1To1_12.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_11_1to1_12/rewriter/EntityPacketRewriter1_12.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_12_2to1_13/Protocol1_12_2To1_13.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_12_2to1_13/rewriter/EntityPacketRewriter1_13.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_12_2to1_13/rewriter/WorldPacketRewriter1_13.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_13_2to1_14/Protocol1_13_2To1_14.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_13_2to1_14/rewriter/EntityPacketRewriter1_14.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_13_2to1_14/rewriter/WorldPacketRewriter1_14.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_13to1_13_1/Protocol1_13To1_13_1.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_13to1_13_1/rewriter/EntityPacketRewriter1_13_1.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_13to1_13_1/rewriter/WorldPacketRewriter1_13_1.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_14_4to1_15/rewriter/EntityPacketRewriter1_15.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_15_2to1_16/rewriter/EntityPacketRewriter1_16.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_16_1to1_16_2/rewriter/EntityPacketRewriter1_16_2.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_16_4to1_17/rewriter/EntityPacketRewriter1_17.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_8to1_9/Protocol1_8To1_9.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_8to1_9/rewriter/PlayerPacketRewriter1_9.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_8to1_9/rewriter/WorldPacketRewriter1_9.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_8to1_9/storage/ClientWorld1_9.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_9_1to1_9_3/Protocol1_9_1To1_9_3.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_9_3to1_10/Protocol1_9_3To1_10.java
- common/src/main/java/com/viaversion/viaversion/rewriter/EntityRewriter.java
This initially makes the ClientWorld object not shared anymore and allows proper dimension switch checks.
Additionally, storages and entities are now only cleared on the actual dimension switch and clearEntities() is called too.
This fixes various issues in the past like the duplicated bossbars in 1.8->1.9.
Closes https://github.com/ViaVersion/ViaFabricPlus/issues/553
> Refactor dimension switch handling across all protocols

- api/src/main/java/com/viaversion/viaversion/api/configuration/ViaVersionConfig.java
- common/src/main/java/com/viaversion/viaversion/configuration/AbstractViaConfig.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_5to1_21/rewriter/BlockItemPacketRewriter1_21.java
- common/src/main/resources/assets/viaversion/config.yml
A vanilla client would send a full movement packet including position and valid on ground as well but this is enough to fix https://github.com/ViaVersion/ViaVersion/issues/4165 and also doesn't need tons of tracking code.
> Add option to fix wrong block placement rotation in 1.20.5->1.21

- common/src/main/java/com/viaversion/viaversion/protocols/v1_8to1_9/storage/EntityTracker1_9.java
The JsonParser#parseString detection in CommonBoss will detect " " as valid json (JsonNull) and won't wrap it around ComponentUtil#plainToJson like it should, at some point in the future I would like CommonBoss to only accept a JsonElement instance and not raw strings anymore.
Closes https://github.com/ViaVersion/ViaFabricPlus/issues/494
> Put title directly into component in 1.8->1.9 bossbar emulation

- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_2to1_20_3/rewriter/BlockItemPacketRewriter1_20_3.java
Should always be printed like in the functions in ComponentUtil
> Print book conversion errors to default logger in 1.20.2->1.20.3

- api/src/main/java/com/viaversion/viaversion/api/data/MappingDataBase.java
Fixes items with block predicates causing disconnections, can be tested with a 1.21.3 client on an older server with: /give @p golden_pickaxe[can_break={predicates:[{blocks:"coal_ore"}],show_in_tooltip:false}] 1
> Fix MappingDataBase#getOldBlockId implementation

- common/src/main/java/com/viaversion/viaversion/protocols/v1_21to1_21_2/rewriter/BlockItemPacketRewriter1_21_2.java
Minecraft 1.21.1 client:
custom_name > item_name > default/generated (e.g. player heads/potions)
Minecraft 1.21.2 client:
custom name > default/generated > item_name
> Fix item_name<->default name priority for items in 1.21->1.21.2

- common/src/main/java/com/viaversion/viaversion/protocols/v1_21to1_21_2/Protocol1_21To1_21_2.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_21to1_21_2/rewriter/BlockItemPacketRewriter1_21_2.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_21to1_21_2/rewriter/EntityPacketRewriter1_21_2.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_21to1_21_2/storage/ChunkLoadTracker.java
1.21.3 no longer allows overwriting an already loaded chunk. To fix this the chunk has to be unloaded first.
Fixes https://github.com/ViaVersion/ViaProxy/issues/313
> Fix 1.21.1 -> 1.21.2 chunk loading edge case

- .gitignore
- common/build.gradle.kts
- gradle/libs.versions.toml
Adds a gradle task which starts ViaProxy with the current code changes. This allows quick and easy testing of new changes without complex server/client mod setup.
Also allows hotswapping if added as IntelliJ run configuration:
> Add gradle task to quickly test/debug code changes

- common/src/main/java/com/viaversion/viaversion/protocols/v1_21to1_21_2/rewriter/BlockItemPacketRewriter1_21_2.java
Fixes conflicting tags with the StructuredItemRewriter base handling
> Use correct tag name for 1.21->1.21.2 item name fix

- common/src/main/java/com/viaversion/viaversion/protocols/v1_21to1_21_2/rewriter/BlockItemPacketRewriter1_21_2.java
Restores the blocking animation for swords on 1.8 or lower servers
This only works on 22w44a+ client due to a client bug. The animation exists in 1.21.3, but doesn't render in first person.
> Change the consume animation of swords to block

- common/build.gradle.kts
Update check isn't needed in this use case
> Skip ViaProxy update check in runViaProxy gradle task

- common/src/main/java/com/viaversion/viaversion/protocols/v1_21to1_21_2/rewriter/BlockItemPacketRewriter1_21_2.java
In 1.8, when picking any container block, with 1.21.3 the client will disconnect with the following protocol error:
```
Caused by: io.netty.handler.codec.DecoderException: Failed to decode: Failed to parse either. First: Failed to parse either. First: Not a string: null; Second: Not a json array: null; Second: Not a JSON object: null missed input: {custom_name:""} {components:{custom_name:""}}
```
> Fix protocol error when an empty lock is sent (picking beacon, etc.)

- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_5to1_21/rewriter/BlockItemPacketRewriter1_21.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_21to1_21_2/rewriter/BlockItemPacketRewriter1_21_2.java
- common/src/main/java/com/viaversion/viaversion/rewriter/StructuredItemRewriter.java
Adds StructuredItemRewriter#removeCustomTag which removes the initial created custom data component if we created it for tracking.
> Properly remove custom_data component if we created it in 1.20.5+ protocols

- common/src/main/java/com/viaversion/viaversion/commands/defaultsubs/ReloadSubCmd.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_5to1_21/rewriter/EntityPacketRewriter1_21.java
Fixes the config option breaking when using the reload command, also changes the message when using the /reload sub command.
> Move config option check for placement fix into packet handlers

- common/src/main/java/com/viaversion/viaversion/protocols/v1_12_2to1_13/rewriter/ItemPacketRewriter1_13.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_15_2to1_16/Protocol1_15_2To1_16.java
We previously had people complaining about this being an error and not understanding what it means + servers can't do anything about these errors anyway.
> Only print invalid custom payload channel warnings in debug mode

- common/src/main/java/com/viaversion/viaversion/protocols/v1_10to1_11/rewriter/EntityPacketRewriter1_11.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_12_2to1_13/Protocol1_12_2To1_13.java
MC <= 1.10.2 had stone as fallback item as long as the entity data wasn't present while 1.11+ doesn't render anything until the entity data is sent.
Closes https://github.com/ViaVersion/ViaFabricPlus/issues/604
> Send default entity data for items in 1.10->1.11

- bukkit/src/main/java/com/viaversion/viaversion/bukkit/listeners/v1_20_5to1_21/LegacyChangeItemListener.java
- bukkit/src/main/java/com/viaversion/viaversion/bukkit/listeners/v1_20_5to1_21/PlayerChangeItemListener.java
- bukkit/src/main/java/com/viaversion/viaversion/bukkit/platform/BukkitViaLoader.java
- common/src/main/java/com/viaversion/viaversion/ViaListener.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_5to1_21/rewriter/BlockItemPacketRewriter1_21.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_5to1_21/rewriter/EntityPacketRewriter1_21.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_5to1_21/storage/EfficiencyAttributeStorage.java
- common/src/main/java/com/viaversion/viaversion/rewriter/ItemRewriter.java
Fixes #4235 
Legacy servers (anything without modern paper PlayerInventorySlotChangeEvent) will attempt to sync enchantments 
in a few occasions:
- punching blocks (efficiency)
- closing inventory (armor)
- the clientbound set container slot packet (armor)
From testing it seems to be working ok (1.8 server) and even if there's still some ways to desync it (eg: right clicking to equip armor) i think it's good enough, worst case scenario reopening the inventory will fix it.
> Improve 1.21 client enchantments in legacy servers

- common/src/main/java/com/viaversion/viaversion/rewriter/BlockRewriter.java
Block ids are not getting remapped, because `getBlockMappings()` is always null as the mappings are not loaded before the registration/initialization.
It's also possible to load the mappings before and wait for all mappings to be loaded (as this is done on an executor thread), but this approach is way less invasive, and still correct.
This only affects players using Geyser at the moment (as Geyser uses the block id to translate block event, chest animation not working etc.), but who knows if Java Edition extends its validation, or alters behavior.
> Fix block ids not getting remapped

- api/src/main/java/com/viaversion/viaversion/api/data/FullMappingsBase.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_21to1_21_2/rewriter/ParticleRewriter1_21_2.java
Added checks for when getMappingData returns null and getParticleMappings returns null.
Also swapped the equals check around to stop null issues.
This fixes the recent bug I found when playing 1.8.x bedwarspractice and was getting kicked when using invis and the footstep particles spawned.
> Fix footstep particle causing null kick

- bukkit/src/main/java/com/viaversion/viaversion/bukkit/providers/BukkitPickItemProvider.java
ItemMeta always gets cloned when accessed - it seems like the set was just forgotten
> Fix item meta not being saved when including block state data

- api/src/main/java/com/viaversion/viaversion/api/configuration/ViaVersionConfig.java
- common/src/main/java/com/viaversion/viaversion/configuration/AbstractViaConfig.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_3to1_20_5/rewriter/BlockItemPacketRewriter1_20_5.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_21_2to1_21_4/rewriter/BlockItemPacketRewriter1_21_4.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_21to1_21_2/rewriter/BlockItemPacketRewriter1_21_2.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_8to1_9/rewriter/WorldPacketRewriter1_9.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_8to1_9/storage/EntityTracker1_9.java
- common/src/main/resources/assets/viaversion/config.yml
This PR has two commits, the first reimplements consumable blocking for 1.21.4 only, and removes all blocking-related shields from 1.21.4 clients, using consumables instead.
The reason consumable blocking is removed for 1.20.5-1.21.3 is that it currently doesn't work properly. With both `shield-blocking` and `sword-blocking-via-consumable` enabled (the former is required to still let 1.9-1.20.4 clients block), blocking in 1.20.5-1.21.3 *seems* to be working on the client, but the block doesn't actually get registered on the server *most of the time*. 
What I believe is happening is that the client starts eating, then when it receives a shield it stops using the item so the block gets cancelled server side. (I checked with a debugger and ViaVersion's `setBlocking` is correctly called with …
> Sword blocking: consumables for 1.21.4+, back to shields for 1.20.5-1.21.3

- .github/ISSUE_TEMPLATE/bug_report.yml
- api/src/main/java/com/viaversion/viaversion/api/platform/ViaPlatform.java
Doesn't work on most implementations and serves no purpose
> Mark ViaPlatform#isPluginEnabled as deprecated

- api/src/main/java/com/viaversion/viaversion/api/minecraft/entities/EntityTypes1_10.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/entities/EntityTypes1_11.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/entities/EntityTypes1_12.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/entities/EntityTypes1_13.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/entities/EntityTypes1_14.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/entities/EntityTypes1_15.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/entities/EntityTypes1_16.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/entities/EntityTypes1_16_2.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/entities/EntityTypes1_17.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/entities/EntityTypes1_19.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/entities/EntityTypes1_19_3.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/entities/EntityTypes1_19_4.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/entities/EntityTypes1_20_3.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/entities/EntityTypes1_20_5.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/entities/EntityTypes1_21_2.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/entities/EntityTypes1_21_4.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/entities/EntityTypes1_8.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/entities/EntityTypes1_9.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_10to1_11/rewriter/EntityPacketRewriter1_11.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_13_2to1_14/rewriter/EntityPacketRewriter1_14.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_8to1_9/rewriter/SpawnPacketRewriter1_9.java
- common/src/main/java/com/viaversion/viaversion/rewriter/EntityRewriter.java
Minecraft <= 1.13.2 silently ignores unknown entity type ids and doesn't print any warning, while we currently still track them. Minecraft 1.14+ will spawn a pig if the entity type is invalid while we track ENTITY as wrong type. Both cases can cause various entity data issues where the server sends wrong data for non-existing entities while we still handle it.
> Fix entity defaults across all protocols

- common/src/main/java/com/viaversion/viaversion/protocols/base/InitialBaseProtocol.java
The packet content has to be modified before wrapper.resetReader() is called, else it will fail
> Fix handshake packet transfer handling

- common/src/main/java/com/viaversion/viaversion/protocols/v1_21_2to1_21_4/rewriter/BlockItemPacketRewriter1_21_4.java
Uses "intentionally_empty" sound event which is no sound, for the consumable blocking in 1.21.4+ on 1.8 server.
> Use "intentionally_empty" sound event for 1.8 blocking

- common/src/main/java/com/viaversion/viaversion/rewriter/RegistryDataRewriter.java
Remove registry entries sent by older servers which do not exist in the current version to prevent duplicated entries when we send default data, assuming the server doesn't send them.
Closes https://github.com/ViaVersion/ViaFabricPlus/issues/683
Closes https://github.com/ViaVersion/ViaFabricPlus/issues/698
> Remove newly added registry entries when already sent be the server

- api/src/main/java/com/viaversion/viaversion/api/debug/DebugHandler.java
- common/src/main/java/com/viaversion/viaversion/commands/defaultsubs/DebugSubCmd.java
- common/src/main/java/com/viaversion/viaversion/debug/DebugHandlerImpl.java
- common/src/main/java/com/viaversion/viaversion/protocol/ProtocolPipelineImpl.java
- velocity/src/main/java/com/viaversion/viaversion/velocity/storage/VelocityStorage.java
Also allows to print packets both before and after packet transformation for debugging purposes and removes the Beta annotation as this API existed for ~3 years now and is not beta anymore.
> Add DebugHandler#logPrePacketTransform/setLogPacketTransform

- common/src/main/java/com/viaversion/viaversion/protocol/ProtocolManagerImpl.java
- common/src/main/java/com/viaversion/viaversion/protocols/base/v1_16/ClientboundBaseProtocol1_16.java
- common/src/main/java/com/viaversion/viaversion/protocols/base/v1_7/ClientboundBaseProtocol1_7.java
ViaAprilFools needs to enforce 1.16 uuid reading for the infinite snapshot and therefore adds the base protocols manually which means we need an own one for this change.
> Treat changes in clientbound base protocol handlers as separate protocols

- api/src/main/java/com/viaversion/viaversion/api/platform/ViaPlatform.java
- common/src/main/java/com/viaversion/viaversion/connection/ConnectionDetails.java
- velocity/src/main/java/com/viaversion/viaversion/VelocityPlugin.java
- velocity/src/main/java/com/viaversion/viaversion/velocity/listeners/ConnectionDetailsListener.java
- velocity/src/main/java/com/viaversion/viaversion/velocity/platform/VelocityViaLoader.java
Adds an optional custom payload protocol which platforms can use to communicate the native version of users across backend servers, the current implementation supports Velocity by sending the player's native version to the backend servers. Platforms may call ConnectionDetails#sendConnectionDetails themselves to ensure the packet getting handled by the server.
Documentation: https://github.com/ViaVersion/ViaVersion/wiki/Player-Details-Protocol
> Add connection details protocol implementation

- api/src/main/java/com/viaversion/viaversion/api/minecraft/Particle.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/RegistryEntry.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/data/EmptyStructuredData.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/data/FilledStructuredData.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/data/StructuredData.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/data/StructuredDataContainer.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/item/Item.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/item/data/AdventureModePredicate.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/item/data/ArmorTrimMaterial.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/item/data/ArmorTrimPattern.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/item/data/AttributeModifiers1_20_5.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/item/data/AttributeModifiers1_21.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/item/data/Bee.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/item/data/BlockPredicate.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/item/data/BlockStateProperties.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/item/data/ChatType.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/item/data/Consumable1_21_2.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/item/data/CustomModelData1_21_4.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/item/data/DeathProtection.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/item/data/Enchantments.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/item/data/FireworkExplosion.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/item/data/Fireworks.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/item/data/FoodProperties1_20_5.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/item/data/Instrument1_21_2.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/item/data/PotDecorations.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/item/data/PotionContents.java
- api/src/main/java/com/viaversion/viaversion/api/minecraft/item/data/WrittenBook.java
- api/src/main/java/com/viaversion/viaversion/util/Copyable.java
Adds a global Copyable interface with a copy() function used in all mutable objects.
Implements proper copy of structured item by copying all structured data elements inside the container.
> Add Copyable interface and unify copy() methods

- common/src/main/java/com/viaversion/viaversion/protocols/v1_21_4to1_21_5/rewriter/ComponentRewriter1_21_5.java
Not sure if the return value should be put through the 1.21.5 serializer first, but that probably doesn't make a difference.
Closes https://github.com/ViaVersion/ViaVersion/issues/4445
Closes https://github.com/ViaVersion/ViaVersion/issues/4437
> Use correct version in json to tag conversion in 1.21.4->.5

- common/src/main/java/com/viaversion/viaversion/protocols/v1_21to1_21_2/rewriter/EntityPacketRewriter1_21_2.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_21to1_21_2/storage/ClientVehicleStorage.java
Local player ticking logic:
1.21:
1.21.2:
> Send player input every tick when in boat in 1.21->1.21.2

- common/src/main/java/com/viaversion/viaversion/rewriter/BlockRewriter.java
- common/src/main/java/com/viaversion/viaversion/util/SerializerVersion.java
Mojang changed block entity type parsing in 1.20.5 to throw on invalid block entities instead of ignoring them, we forgot to update our handle for newer protocols which will now kick if you join with a 1.21.4 client on a 1.21.5 server and set a test block. As this change should not hurt in older versions (as an invalid id would also cause the data to be ignored) I decided to put this directly instead of having multiple register methods.
> Cancel unknown block entities in BlockRewriter#registerBlockEntityData 

- common/src/main/java/com/viaversion/viaversion/protocols/v1_21_4to1_21_5/rewriter/ComponentRewriter1_21_5.java
- common/src/main/java/com/viaversion/viaversion/rewriter/text/NBTComponentRewriter.java
The input version needs to be overridden for the convertLegacyItemContents/convertLegacyEntityContents, and we also need to map the entity type (potion->splash_potion)
> Fix legacy item/entity hover events in 1.21.4->1.21.5

- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_3to1_20_5/Protocol1_20_3To1_20_5.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_5to1_21/Protocol1_20_5To1_21.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_21_2to1_21_4/Protocol1_21_2To1_21_4.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_21to1_21_2/Protocol1_21To1_21_2.java
- common/src/main/java/com/viaversion/viaversion/rewriter/text/JsonNBTComponentRewriter.java
This PR fixes a network protocol error which occures if a signed chat message contains a show item hover event with an old custom model data.
Example log: https://mclo.gs/rlpXuL8
> Add missing PLAYER_CHAT handlers in 1.20/1.21 versions

- common/build.gradle.kts
- gradle/libs.versions.toml
This will otherwise break when Gradle 9+ versions hits as they will require that to be done; see https://github.com/gradle/gradle/pull/24189
> Include platform launcher runtime dependency for tests

- api/src/main/java/com/viaversion/viaversion/api/type/types/chunk/PaletteType1_18.java
Minecraft has its own ZeroBitStorage type for this case so we don't need to perform the validation, also removed the comments as this is just how our code should work to match Vanilla behaviour (at least for the first one; I did not verify the readValues code)
Closes https://github.com/ViaVersion/ViaVersion/issues/4476
> Don't perform length validation on zero bit storage in 1.18 palette type

- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_3to1_20_5/rewriter/BlockItemPacketRewriter1_20_5.java
In 1.20.5, codecs introduced the non-negative int type which will fail if a value <= 0 is present. In 1.20.4, Mojang gracefully handled negative values.
Fixes https://github.com/ViaVersion/ViaFabricPlus/issues/763
> Check for non-negative value for damage & repair cost in 1.20.3->.5

- api/src/main/java/com/viaversion/viaversion/api/minecraft/HolderSetImpl.java
In VB, mapping data will return -1 for missing block ids (which is for almost all blocks the case). This is made so that VV rewriters can cancel these blocks away nicely (as mostly used in places where it's better to show the user nothing rather than wrong blocks, such as statistics).
Fixes https://github.com/ViaVersion/ViaVersion/issues/4510
> Cancel out unmapped (block) ids in HolderSetImpl

- common/src/main/java/com/viaversion/viaversion/protocols/v1_21to1_21_2/Protocol1_21To1_21_2.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_21to1_21_2/rewriter/EntityPacketRewriter1_21_2.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_21to1_21_2/storage/EntityTracker1_21_2.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_21to1_21_2/storage/TeleportAckCancelStorage.java
Fixes being unable to respawn. Caused by a change in Minecraft where <=1.21.1 clients reset some player data after respawning, while >=1.21.2 clients do not
1.21.1:
1.21.2:
> Fix respawning with 1.21.2+ clients on older vanilla servers

- common/src/main/java/com/viaversion/viaversion/protocols/v1_21_4to1_21_5/rewriter/ComponentRewriter1_21_5.java
Minecraft versions prior to 1.21.4 filter out invalid characters when handling the click event on the clientside while 1.21.5+ validates and throws in the network codec per ExtraCodecs#CHAT_STRING
> Filter invalid characters in command click events in 1.21.4->.5

- bukkit/src/main/java/com/viaversion/viaversion/bukkit/providers/BukkitPickItemProvider.java
As discussed in https://github.com/ViaVersion/ViaVersion/pull/4412, some forks provide the `Material#isItem()` Method for convenience, breaking the legacy support detection.
This PR changes the legacy provider to always be used when all class/method resolutions succeed during class initialization.
> Fix legacy block picking on some paper forks

- api/src/main/java/com/viaversion/viaversion/api/configuration/ViaVersionConfig.java
- common/src/main/java/com/viaversion/viaversion/configuration/AbstractViaConfig.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_11_1to1_12/Protocol1_11_1To1_12.java
- common/src/main/resources/assets/viaversion/config.yml
I should have removed that when I rewrote the chat item rewriters in that protocol, but I somehow forgot.
> Remove arbitrary chat-nbt-fix config option in 1.11.1->1.12

- api/src/main/java/com/viaversion/viaversion/api/connection/StorableObject.java
- api/src/main/java/com/viaversion/viaversion/api/connection/UserConnection.java
- common/src/main/java/com/viaversion/viaversion/connection/UserConnectionImpl.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_18_2to1_19/storage/DimensionRegistryStorage.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_19to1_19_1/storage/ChatTypeStorage.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_3to1_20_5/storage/AcknowledgedMessagesStorage.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_3to1_20_5/storage/BannerPatternStorage.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_20to1_20_2/storage/ConfigurationState.java
- common/src/main/java/com/viaversion/viaversion/protocols/v1_20to1_20_2/storage/LastResourcePack.java
This was only ever used on BungeeCord and was most likely wrong / a workaround from otherwise broken code. I think we can finally get rid of it.
> Remove StorableObject#clearOnServerSwitch

- settings.gradle.kts
Allows the project to compile even when JDK 17 is not natively installed.
> [ci skip] Add Java resolving plugin

- gradle/libs.versions.toml
As title says.
ViaVersion compiles just fine and the issue with deserializing SNBT with zero signed byte tags is fixed.
> Update ViaNBT dependency from 5.1.0 to 5.1.2

- common/src/main/java/com/viaversion/viaversion/protocols/v1_21_4to1_21_5/rewriter/BlockItemPacketRewriter1_21_5.java
- gradle.properties
- gradle/libs.versions.toml
Fixes it not being set in VB. I decided to remove the backup tag as this is the closest replacement / should work fine in VV too.
> Convert HIDE_ADDITIONAL_TOOLTIP in both directions in 1.21.4->1.21.5

- common/src/main/java/com/viaversion/viaversion/connection/ConnectionManagerImpl.java
This fixes the issue with proxy plugin messaging channel where the message is only sent to the first server they join due to getClientConnection returning null. This is due to it getting removed after they switch server.
This fixes #4565
> fix: Proxy Plugin Messaging Channel 

- common/src/main/java/com/viaversion/viaversion/protocols/v1_21_4to1_21_5/rewriter/ComponentRewriter1_21_5.java
I don't think this ever was an inlined string for show_text. At least in 1.21.4, /tellraw doesn't work with it + can't find anything about it in MC or in MCStructs. would appreciate if you could confirm/verify
> Don't put legacy show_text value through json conversion in 1.21.4->.5

- common/src/main/java/com/viaversion/viaversion/protocols/v1_20to1_20_2/Protocol1_20To1_20_2.java
Fixes [#4478](https://github.com/ViaVersion/ViaVersion/issues/4478)
The problem was introduced in commit [18c4f90](https://github.com/ViaVersion/ViaVersion/commit/18c4f90cb0ed6fc9ca7b2d2d194663ff81343628) to fix an additional message being sent by the Vanilla server.
I checked the Vanilla source code and the "exceptional" message was introduced in Minecraft 1.13 and as far as I can see has been kept in the latest versions.
```java
@Override
public void sendMessage(final IChatBaseComponent ichatbasecomponent) {
this.playerConnection.sendPacket(new PacketPlayOutChat(ichatbasecomponent));
}
```
```java
@Override
public void sendMessage(final IChatBaseComponent ichatbasecomponent) {
this.a(ichatbasecomponent, ChatMessageType.SYSTEM);
}
public void a(final IChatBaseComponent …
```
> Fix: System chat messages sent during configuration are hidden on 1.8 servers behind Velocity

- common/src/main/java/com/viaversion/viaversion/protocols/v1_20_3to1_20_5/storage/ScoreboardTeamStorage.java
In the vanilla client, if it receives a "Add Player to Team" packet, it will automatically remove the player from any other team the client thinks the player is on
However, the fix from PR #4643 does not do this, and is storing the team of the player when the player is possibly not on that team by the clients knowledge
So I figured I would make a PR to address this minor thing
> Fix "Filter Invalid Teams Packet" fix storing teams of players which the client does not store
